# Evaluation: Modelling Node
This notebook evaluates `modelling` predictions against benchmark labels and includes a concise first-iteration utility for reruns.

In [1]:
# Setup imports and project paths
import os
import sys
import json
from pathlib import Path

import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# Resolve project root robustly from notebook location
ROOT = Path.cwd().resolve()
if not (ROOT / "nodes").exists():
    ROOT = ROOT.parent
if not (ROOT / "nodes").exists():
    ROOT = ROOT.parent

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

PILOT = ROOT / "Pilot_Evaluation"
BENCHMARK_FILE = PILOT / "DATA_sample_10" / "Data Science Research Process (DSRP) Framework.csv"
RESULTS_FOLDER = PILOT / "pilot_study_results"
VECTOR_DB_PATH = PILOT / "pilot_study_10_vectors"
COLLECTION_NAME = "pilot_study_10"
EMBEDDING_MODEL = "text-embedding-3-small"

print(f"Project root: {ROOT}")
print(f"Benchmark file exists: {BENCHMARK_FILE.exists()}")
print(f"Results folder exists: {RESULTS_FOLDER.exists()}")

Project root: C:\Users\sahil\OneDrive\PhD\3. Empirical Study\Methodological Workflow
Benchmark file exists: True
Results folder exists: True

In [2]:
# Load benchmark and define modelling helpers
DIMENSIONS = [
    "Foundational Paradigm",
    "ML Learning Type",
    "ML Problem Type",
    "Deep Learning Used",
    "Specialised Paradigms",
]

PRED_KEY_MAP = {
    "Foundational Paradigm": "foundational_paradigm",
    "ML Learning Type": "ml_learning_type",
    "ML Problem Type": "ml_problem_type",
    "Deep Learning Used": "deep_learning_used",
    "Specialised Paradigms": "specialised_paradigms",
}

LIST_DIMENSIONS = {"ML Learning Type", "ML Problem Type", "Specialised Paradigms"}

FOUNDATIONAL_ALLOWED = [
    "Classical Statistical Modelling",
    "Machine Learning",
    "Mixed",
]

ML_LEARNING_ALLOWED = ["supervised", "unsupervised", "reinforcement", "not_applicable"]
ML_PROBLEM_ALLOWED = [
    "classification",
    "regression",
    "clustering",
    "dimensionality reduction",
    "reward optimisation",
    "not_applicable",
]
SPECIALISED_ALLOWED = [
    "Time-Series Analytics",
    "Natural Language Processing",
    "Spatial Analytics",
    "Network Analysis",
    "Emerging Paradigms",
]

def normalize_text(value):
    if value is None or pd.isna(value):
        return None
    text = str(value).strip()
    return text if text else None

def normalize_paper_id(value):
    text = normalize_text(value)
    return text.lower() if text else None

def normalize_bool(value):
    text = normalize_text(value)
    if not text:
        return False
    return text.lower() in {"true", "1", "yes", "y"}

def normalize_foundational(value):
    text = normalize_text(value)
    if not text:
        return None
    for canonical in FOUNDATIONAL_ALLOWED:
        if text.lower() == canonical.lower():
            return canonical
    return text

def _split_semicolon(value):
    text = normalize_text(value)
    if not text:
        return []
    return [p.strip() for p in text.split(";") if p and str(p).strip()]

def normalize_ml_learning(values):
    if not isinstance(values, list):
        values = _split_semicolon(values)
    mapping = {
        "supervised": "supervised",
        "supervised learning": "supervised",
        "unsupervised": "unsupervised",
        "unsupervised learning": "unsupervised",
        "reinforcement": "reinforcement",
        "reinforcement learning": "reinforcement",
        "not applicable": "not_applicable",
        "not_applicable": "not_applicable",
    }
    out = []
    for item in values:
        text = normalize_text(item)
        if not text:
            continue
        mapped = mapping.get(text.lower(), text.lower())
        if mapped not in out:
            out.append(mapped)
    return sorted(out)

def normalize_ml_problem(values):
    if not isinstance(values, list):
        values = _split_semicolon(values)
    mapping = {
        "classification": "classification",
        "regression": "regression",
        "clustering": "clustering",
        "dimensionality reduction": "dimensionality reduction",
        "dimensionality_reduction": "dimensionality reduction",
        "reward optimisation": "reward optimisation",
        "reward optimization": "reward optimisation",
        "not applicable": "not_applicable",
        "not_applicable": "not_applicable",
    }
    out = []
    for item in values:
        text = normalize_text(item)
        if not text:
            continue
        mapped = mapping.get(text.lower(), text.lower())
        if mapped not in out:
            out.append(mapped)
    return sorted(out)

def normalize_specialised(values):
    if not isinstance(values, list):
        values = _split_semicolon(values)
    out = []
    for item in values:
        text = normalize_text(item)
        if not text:
            continue
        matched = None
        for canonical in SPECIALISED_ALLOWED:
            if text.lower() == canonical.lower():
                matched = canonical
                break
        out.append(matched or text)
    return sorted(set(out))

def normalize_dimension(dim, value):
    if dim == "Foundational Paradigm":
        return normalize_foundational(value)
    if dim == "ML Learning Type":
        return normalize_ml_learning(value)
    if dim == "ML Problem Type":
        return normalize_ml_problem(value)
    if dim == "Deep Learning Used":
        return normalize_bool(value)
    if dim == "Specialised Paradigms":
        return normalize_specialised(value)
    return value

def format_dimension_value(dim, value):
    if dim in LIST_DIMENSIONS:
        return "; ".join(value) if value else "[]"
    if isinstance(value, bool):
        return str(value)
    return str(value) if value is not None else "(missing)"

def list_jaccard(gt_list, pred_list):
    gt_set = set(gt_list or [])
    pred_set = set(pred_list or [])
    if not gt_set and not pred_set:
        return 1.0
    return len(gt_set & pred_set) / len(gt_set | pred_set)

def get_nested(data, path, default=None):
    current = data
    for key in path.split("."):
        if not isinstance(current, dict) or key not in current:
            return default
        current = current[key]
    return current

benchmark_df = pd.read_csv(BENCHMARK_FILE)
benchmark_df.columns = benchmark_df.columns.str.strip()

benchmark_col_map = {
    "Specialised Paradigms": "Specialised Paradigms (Skip if none)",
}
required_cols = ["Paper ID", "Gatekeeper", "Foundational Paradigm", "ML Learning Type", "ML Problem Type", "Deep Learning Used", benchmark_col_map["Specialised Paradigms"]]
missing = [c for c in required_cols if c not in benchmark_df.columns]
if missing:
    raise ValueError(f"Missing required benchmark columns: {missing}")

benchmark_eval = benchmark_df[required_cols].copy()
benchmark_eval = benchmark_eval.rename(columns={benchmark_col_map["Specialised Paradigms"]: "Specialised Paradigms"})
benchmark_eval["Paper ID"] = benchmark_eval["Paper ID"].apply(normalize_paper_id)
benchmark_eval["Gatekeeper"] = benchmark_eval["Gatekeeper"].astype(str).str.strip().str.lower()

for dim in DIMENSIONS:
    benchmark_eval[dim] = benchmark_eval[dim].apply(lambda v: normalize_dimension(dim, v))

benchmark_eval = benchmark_eval[benchmark_eval["Gatekeeper"] == "include"].copy()
benchmark_eval = benchmark_eval.dropna(subset=["Paper ID"]).reset_index(drop=True)

print(f"Included benchmark rows: {len(benchmark_eval)}")
preview_cols = ["Paper ID", *DIMENSIONS]
print(benchmark_eval[preview_cols].head().to_string(index=False))

Included benchmark rows: 7
 Paper ID           Foundational Paradigm           ML Learning Type              ML Problem Type  Deep Learning Used                                Specialised Paradigms
 2018 - 8                           Mixed               [supervised] [classification, regression]               False                                                   []
2019 - 33 Classical Statistical Modelling                         []                           []               False                                                   []
 2020 - 8                Machine Learning             [unsupervised]                 [clustering]               False      [Natural Language Processing, Network Analysis]
2021 - 28                           Mixed               [supervised]                 [regression]               False                                                   []
2021 - 56                           Mixed [supervised, unsupervised]     [clustering, regression]               False [Natural Language Processing, Time-Series Analytics]

In [3]:
# Load existing agent outputs and build comparison table
def load_agent_results(results_folder: Path):
    agent_data = {}
    for paper_dir in sorted(results_folder.glob("*/")):
        if not paper_dir.is_dir():
            continue
        results_file = paper_dir / "aggregated" / "results.json"
        if not results_file.exists():
            continue
        with open(results_file, "r", encoding="utf-8") as f:
            agent_data[paper_dir.name.strip().lower()] = json.load(f)
    return agent_data

def extract_modelling_prediction(modelling_obj, dim):
    key = PRED_KEY_MAP[dim]
    return normalize_dimension(dim, modelling_obj.get(key))

agent_data = load_agent_results(RESULTS_FOLDER)
print(f"Loaded aggregated outputs for {len(agent_data)} papers")

comparison_rows = []
missing_agent_results = []

for _, row in benchmark_eval.iterrows():
    paper_id = row["Paper ID"]
    if paper_id not in agent_data:
        missing_agent_results.append(paper_id)
        continue

    outputs = agent_data[paper_id]
    modelling_obj = get_nested(outputs, "dsrp_outputs.modelling", default={})

    record = {"Paper ID": paper_id}
    dim_match_flags = []
    for dim in DIMENSIONS:
        gt_value = normalize_dimension(dim, row[dim])
        pred_value = extract_modelling_prediction(modelling_obj, dim)
        is_match = gt_value == pred_value
        dim_match_flags.append(is_match)

        record[f"GT_{dim}"] = format_dimension_value(dim, gt_value)
        record[f"Agent_{dim}"] = format_dimension_value(dim, pred_value)
        record[f"Match_{dim}"] = "MATCH" if is_match else "MISMATCH"

        if dim in LIST_DIMENSIONS:
            record[f"Jaccard_{dim}"] = list_jaccard(gt_value, pred_value)

    record["Match_All_5"] = "MATCH" if all(dim_match_flags) else "MISMATCH"
    comparison_rows.append(record)

comparison_df = pd.DataFrame(comparison_rows)
print(f"Comparable rows: {len(comparison_df)}")
if missing_agent_results:
    print(f"Missing agent outputs for {len(missing_agent_results)} papers: {', '.join(missing_agent_results)}")

if len(comparison_df):
    show_cols = ["Paper ID", *[f"Match_{d}" for d in DIMENSIONS], "Match_All_5"]
    print(comparison_df[show_cols].to_string(index=False))
else:
    print("No comparable rows found.")

Loaded aggregated outputs for 10 papers
Comparable rows: 7
 Paper ID Match_Foundational Paradigm Match_ML Learning Type Match_ML Problem Type Match_Deep Learning Used Match_Specialised Paradigms Match_All_5
 2018 - 8                       MATCH                  MATCH                 MATCH                    MATCH                       MATCH       MATCH
2019 - 33                       MATCH                  MATCH                 MATCH                    MATCH                       MATCH       MATCH
 2020 - 8                       MATCH                  MATCH                 MATCH                    MATCH                    MISMATCH    MISMATCH
2021 - 28                       MATCH                  MATCH                 MATCH                    MATCH                       MATCH       MATCH
2021 - 56                       MATCH               MISMATCH              MISMATCH                    MATCH                    MISMATCH    MISMATCH
2023 - 58                    MISMATCH               MISMATCH              MISMATCH                    MATCH                    MISMATCH    MISMATCH
2024 - 99                       MATCH               MISMATCH                 MATCH                    MATCH                       MATCH    MISMATCH

In [4]:
# Dimension-wise metrics and overall agreement
if len(comparison_df) == 0:
    raise ValueError("No rows available for evaluation.")

metrics_rows = []
for dim in DIMENSIONS:
    y_true = comparison_df[f"GT_{dim}"].tolist()
    y_pred = comparison_df[f"Agent_{dim}"].tolist()

    acc = accuracy_score(y_true, y_pred)
    precision_macro = precision_score(y_true, y_pred, average="macro", zero_division=0)
    recall_macro = recall_score(y_true, y_pred, average="macro", zero_division=0)
    f1_macro = f1_score(y_true, y_pred, average="macro", zero_division=0)

    row = {
        "dimension": dim,
        "samples": len(y_true),
        "accuracy": acc,
        "precision_macro": precision_macro,
        "recall_macro": recall_macro,
        "f1_macro": f1_macro,
    }

    if dim in LIST_DIMENSIONS:
        row["avg_jaccard"] = comparison_df[f"Jaccard_{dim}"].mean()

    metrics_rows.append(row)

    print("=" * 90)
    print(f"DIMENSION: {dim}")
    print("=" * 90)
    print(f"accuracy............ {acc:.4f}")
    print(f"precision_macro..... {precision_macro:.4f}")
    print(f"recall_macro........ {recall_macro:.4f}")
    print(f"f1_macro............ {f1_macro:.4f}")
    if dim in LIST_DIMENSIONS:
        print(f"avg_jaccard......... {comparison_df[f'Jaccard_{dim}'].mean():.4f}")

    report = classification_report(
        y_true,
        y_pred,
        zero_division=0,
        output_dict=True,
    )
    report_df = pd.DataFrame(report).T
    print("\nPer-label report:")
    print(report_df.to_string())

metrics_df = pd.DataFrame(metrics_rows)
overall_match_count = int((comparison_df["Match_All_5"] == "MATCH").sum())
overall_total = len(comparison_df)
print("\nSUMMARY TABLE")
print(metrics_df.to_string(index=False))
print(f"\nOverall exact agreement across all 5 modelling dimensions: {overall_match_count}/{overall_total} ({100 * overall_match_count / overall_total:.1f}%)")

==========================================================================================
DIMENSION: Foundational Paradigm
==========================================================================================
accuracy............ 0.8571
precision_macro..... 0.9167
recall_macro........ 0.8889
f1_macro............ 0.8857

Per-label report:
                                 precision    recall  f1-score   support
Classical Statistical Modelling   1.000000  1.000000  1.000000  1.000000
Machine Learning                  1.000000  0.666667  0.800000  3.000000
Mixed                             0.750000  1.000000  0.857143  3.000000
accuracy                          0.857143  0.857143  0.857143  0.857143
macro avg                         0.916667  0.888889  0.885714  7.000000
weighted avg                      0.892857  0.857143  0.853061  7.000000
==========================================================================================
DIMENSION: ML Learning Type
==========================================================================================
accuracy............ 0.5714
precision_macro..... 0.3611
recall_macro........ 0.4167
f1_macro............ 0.3556
avg_jaccard......... 0.6429

Per-label report:
                             precision    recall  f1-score   support
[]                            0.500000  1.000000  0.666667  1.000000
optimization-based learning   0.000000  0.000000  0.000000  1.000000
reinforcement                 0.000000  0.000000  0.000000  0.000000
supervised                    0.666667  1.000000  0.800000  2.000000
supervised; unsupervised      0.000000  0.000000  0.000000  1.000000
unsupervised                  1.000000  0.500000  0.666667  2.000000
accuracy                      0.571429  0.571429  0.571429  0.571429
macro avg                     0.361111  0.416667  0.355556  7.000000
weighted avg                  0.547619  0.571429  0.514286  7.000000
==========================================================================================
DIMENSION: ML Problem Type
==========================================================================================
accuracy............ 0.7143
precision_macro..... 0.6667
recall_macro........ 0.7500
f1_macro............ 0.6667
avg_jaccard......... 0.7857

Per-label report:
                            precision    recall  f1-score   support
[]                           0.500000  1.000000  0.666667  1.000000
classification; regression   1.000000  1.000000  1.000000  1.000000
clustering                   1.000000  0.500000  0.666667  2.000000
clustering; regression       0.000000  0.000000  0.000000  1.000000
regression                   0.500000  1.000000  0.666667  1.000000
reward optimisation          1.000000  1.000000  1.000000  1.000000
accuracy                     0.714286  0.714286  0.714286  0.714286
macro avg                    0.666667  0.750000  0.666667  7.000000
weighted avg                 0.714286  0.714286  0.666667  7.000000
==========================================================================================
DIMENSION: Deep Learning Used
==========================================================================================
accuracy............ 1.0000
precision_macro..... 1.0000
recall_macro........ 1.0000
f1_macro............ 1.0000

Per-label report:
              precision  recall  f1-score  support
False               1.0     1.0       1.0      7.0
accuracy            1.0     1.0       1.0      1.0
macro avg           1.0     1.0       1.0      7.0
weighted avg        1.0     1.0       1.0      7.0
==========================================================================================
DIMENSION: Specialised Paradigms
==========================================================================================
accuracy............ 0.5714
precision_macro..... 0.1667
recall_macro........ 0.1667
f1_macro............ 0.1667
avg_jaccard......... 0.7619

Per-label report:
                                                                    precision    recall  f1-score   support
Emerging Paradigms; Natural Language Processing; Spatial Analytics   0.000000  0.000000  0.000000  1.000000
Natural Language Processing                                          0.000000  0.000000  0.000000  0.000000
Natural Language Processing; Network Analysis                        0.000000  0.000000  0.000000  1.000000
Natural Language Processing; Time-Series Analytics                   0.000000  0.000000  0.000000  1.000000
Time-Series Analytics                                                0.000000  0.000000  0.000000  0.000000
[]                                                                   1.000000  1.000000  1.000000  4.000000
accuracy                                                             0.571429  0.571429  0.571429  0.571429
macro avg                                                            0.166667  0.166667  0.166667  7.000000
weighted avg                                                         0.571429  0.571429  0.571429  7.000000

SUMMARY TABLE
            dimension  samples  accuracy  precision_macro  recall_macro  f1_macro  avg_jaccard
Foundational Paradigm        7  0.857143         0.916667      0.888889  0.885714          NaN
     ML Learning Type        7  0.571429         0.361111      0.416667  0.355556     0.642857
      ML Problem Type        7  0.714286         0.666667      0.750000  0.666667     0.785714
   Deep Learning Used        7  1.000000         1.000000      1.000000  1.000000          NaN
Specialised Paradigms        7  0.571429         0.166667      0.166667  0.166667     0.761905

Overall exact agreement across all 5 modelling dimensions: 3/7 (42.9%)

In [5]:
# Detailed mismatch diagnostics
mismatch_df = comparison_df[comparison_df["Match_All_5"] == "MISMATCH"].copy()
print(f"Total mismatched papers: {len(mismatch_df)}")
if len(mismatch_df):
    show_cols = [
        "Paper ID",
        *[f"GT_{d}" for d in DIMENSIONS],
        *[f"Agent_{d}" for d in DIMENSIONS],
        *[f"Match_{d}" for d in DIMENSIONS],
        "Match_All_5",
    ]
    print(mismatch_df[show_cols].to_string(index=False))
else:
    print("No mismatches found.")

Total mismatched papers: 4
 Paper ID GT_Foundational Paradigm         GT_ML Learning Type     GT_ML Problem Type GT_Deep Learning Used                                           GT_Specialised Paradigms Agent_Foundational Paradigm Agent_ML Learning Type Agent_ML Problem Type Agent_Deep Learning Used Agent_Specialised Paradigms Match_Foundational Paradigm Match_ML Learning Type Match_ML Problem Type Match_Deep Learning Used Match_Specialised Paradigms Match_All_5
 2020 - 8         Machine Learning                unsupervised             clustering                 False                      Natural Language Processing; Network Analysis            Machine Learning           unsupervised            clustering                    False Natural Language Processing                       MATCH                  MATCH                 MATCH                    MATCH                    MISMATCH    MISMATCH
2021 - 56                    Mixed    supervised; unsupervised clustering; regression                 False                 Natural Language Processing; Time-Series Analytics                       Mixed             supervised            regression                    False       Time-Series Analytics                       MATCH               MISMATCH              MISMATCH                    MATCH                    MISMATCH    MISMATCH
2023 - 58         Machine Learning                unsupervised             clustering                 False Emerging Paradigms; Natural Language Processing; Spatial Analytics                       Mixed                     []                    []                    False Natural Language Processing                    MISMATCH               MISMATCH              MISMATCH                    MATCH                    MISMATCH    MISMATCH
2024 - 99         Machine Learning optimization-based learning    reward optimisation                 False                                                                 []            Machine Learning          reinforcement   reward optimisation                    False                          []                       MATCH               MISMATCH                 MATCH                    MATCH                       MATCH    MISMATCH

## Iteration Utility
Use the function below to re-run `modelling_node` on selected papers while keeping iteration code out of analysis cells.

In [6]:
import importlib
import textwrap
import nodes.modelling_node as modelling_module
from utils.dsrp_state import DSRPState

def _format_bibliography_text(bibliography):
    entries = bibliography or []
    if not entries:
        return ["(no bibliography)"]
    lines = []
    for i, b in enumerate(entries, start=1):
        sec = b.get("section", "")
        page = b.get("page", "")
        quote = b.get("direct_quote", "")
        lines.append(f"[{i}] page={page} | section={sec}")
        if quote:
            wrapped = textwrap.wrap(str(quote), width=110)
            if wrapped:
                lines.extend([f"    quote: {wrapped[0]}"] + [f"           {w}" for w in wrapped[1:]])
    return lines

def _extract_reasoning_payload(modelling_obj):
    return {
        "overall_validated_reasoning": modelling_obj.get("validated_reasoning", ""),
        "audit_commentary": modelling_obj.get("audit_commentary", ""),
        "confidence": modelling_obj.get("confidence", None),
        "validated_bibliography_count": len(modelling_obj.get("validated_bibliography", []) or []),
        "validated_bibliography_lines": _format_bibliography_text(modelling_obj.get("validated_bibliography", [])),
    }

def _print_iteration_pretty(record, show_bibliography=True):
    print("\n" + "=" * 100)
    print(f"PAPER: {record.get('Paper ID', '(missing)')} | MODEL: {record.get('Model', '(missing)')}")
    print("=" * 100)
    if record.get("Error"):
        print(f"Error: {record['Error']}")
        return

    for dim in DIMENSIONS:
        print(f"\n{dim}")
        print(f"  GT    : {record.get(f'GT_{dim}', '(missing)')}")
        print(f"  Agent : {record.get(f'New_Agent_{dim}', '(missing)')}")
        print(f"  Match : {record.get(f'Match_{dim}', '(missing)')}")

    print("\nOverall all-5-dimensions match:", record.get("Match_All_5", "(missing)"))
    print("Confidence:", record.get("confidence", "(missing)"))
    print("Overall validated reasoning:")
    reasoning = str(record.get("overall_validated_reasoning", "") or "(none)")
    for line in textwrap.wrap(reasoning, width=110):
        print(f"  {line}")
    print("Audit commentary:")
    commentary = str(record.get("audit_commentary", "") or "(none)")
    for line in textwrap.wrap(commentary, width=110):
        print(f"  {line}")
    if show_bibliography:
        print("Bibliography:")
        for line in record.get("validated_bibliography_lines", ["(no bibliography)"]):
            print(f"  {line}")

def run_modelling_iteration(
    paper_ids,
    llm_model="gpt-4o-mini",
    verbose=True,
    include_reasoning=True,
    show_reasoning_in_logs=False,
    log_bibliography=False,
    ):
    """Run modelling_node over selected papers and return a compact comparison table."""
    importlib.reload(modelling_module)
    modelling_node = modelling_module.modelling_node

    benchmark_lookup = benchmark_eval.set_index("Paper ID")
    rows = []

    original_dir = Path.cwd().resolve()
    os.chdir(ROOT)
    try:
        for paper_id in paper_ids:
            pid = normalize_paper_id(paper_id)
            if not pid:
                continue
            if pid not in benchmark_lookup.index:
                rows.append({"Paper ID": pid, "Error": "Paper ID not found in benchmark include set"})
                continue

            print(f"Re-running modelling node for {pid} with {llm_model}...")
            state = DSRPState(
                paper_id=pid,
                gatekeeper={},
                dsrp_outputs={},
                collection_name=COLLECTION_NAME,
                persist_directory=str(VECTOR_DB_PATH),
                embedding_model=EMBEDDING_MODEL,
                llm_model=llm_model,
            )

            try:
                out = modelling_node(state)
                modelling_obj = get_nested(out, "dsrp_outputs.modelling", default={})

                record = {"Paper ID": pid, "Model": llm_model}
                match_flags = []
                for dim in DIMENSIONS:
                    gt_value = normalize_dimension(dim, benchmark_lookup.loc[pid, dim])
                    pred_value = normalize_dimension(dim, modelling_obj.get(PRED_KEY_MAP[dim]))
                    dim_match = gt_value == pred_value
                    match_flags.append(dim_match)

                    record[f"GT_{dim}"] = format_dimension_value(dim, gt_value)
                    record[f"New_Agent_{dim}"] = format_dimension_value(dim, pred_value)
                    record[f"Match_{dim}"] = "MATCH" if dim_match else "MISMATCH"

                if include_reasoning:
                    record.update(_extract_reasoning_payload(modelling_obj))

                record["Match_All_5"] = "MATCH" if all(match_flags) else "MISMATCH"
                rows.append(record)

                if verbose:
                    label_line = " | ".join(
                        f"{dim}: {record.get(f'New_Agent_{dim}', '(missing)')}"
                        for dim in DIMENSIONS
                    )
                    print(f"  Assigned labels -> {label_line}")
                    print(f"  Match_All_5: {record['Match_All_5']}")

                if verbose and include_reasoning and show_reasoning_in_logs:
                    _print_iteration_pretty(record, show_bibliography=log_bibliography)

            except Exception as e:
                err_row = {"Paper ID": pid, "Model": llm_model, "Error": str(e)}
                rows.append(err_row)
                if verbose:
                    print(f"  Error: {e}")
    finally:
        os.chdir(original_dir)

    retest_df = pd.DataFrame(rows)
    if len(retest_df):
        print("\n" + "-" * 110)
        print("RE-TEST RESULTS (compact summary)")
        print("-" * 110)
        show_cols = [
            "Paper ID",
            "Model",
            *[col for d in DIMENSIONS for col in (f"GT_{d}", f"New_Agent_{d}", f"Match_{d}")],
            "Match_All_5",
        ]
        cols = [c for c in show_cols if c in retest_df.columns]
        if cols:
            print(retest_df[cols].to_string(index=False))
        else:
            print(retest_df.to_string(index=False))
    return retest_df

def show_iteration_reasoning(retest_df, paper_id, show_bibliography=True):
    pid = normalize_paper_id(paper_id)
    if "Paper ID" not in retest_df.columns:
        raise ValueError("retest_df does not contain 'Paper ID'.")

    rows = retest_df[retest_df["Paper ID"] == pid]
    if len(rows) == 0:
        raise ValueError(f"Paper ID not found in retest_df: {pid}")

    row = rows.iloc[0].to_dict()
    _print_iteration_pretty(row, show_bibliography=show_bibliography)

## Iteration 1
Run a single first iteration on mismatched papers from the baseline comparison.

In [18]:
# Iteration 1: baseline rerun on papers mismatched in baseline outputs
papers_to_rerun = comparison_df[comparison_df["Match_All_5"] == "MISMATCH"]["Paper ID"].tolist()
print(f"Papers selected for Iteration 1 rerun: {len(papers_to_rerun)}")

retest_df = run_modelling_iteration(
    paper_ids=papers_to_rerun,
    llm_model="gpt-4o-mini",
    verbose=True,
    include_reasoning=True,
    show_reasoning_in_logs=False,
    log_bibliography=False,
)

Papers selected for Iteration 1 rerun: 4
Re-running modelling node for 2020 - 8 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Machine Learning | ML Learning Type: unsupervised | ML Problem Type: clustering | Deep Learning Used: False | Specialised Paradigms: Natural Language Processing
  Match_All_5: MISMATCH
Re-running modelling node for 2021 - 56 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Mixed | ML Learning Type: supervised | ML Problem Type: regression | Deep Learning Used: False | Specialised Paradigms: Natural Language Processing; Time-Series Analytics
  Match_All_5: MISMATCH
Re-running modelling node for 2023 - 58 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Mixed | ML Learning Type: unsupervised | ML Problem Type: clustering | Deep Learning Used: False | Specialised Paradigms: Emerging Paradigms; Natural Language Processing; Spatial Analytics
  Match_All_5: MISMATCH
Re-running modelling node for 2024 - 99 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Machine Learning | ML Learning Type: [] | ML Problem Type: [] | Deep Learning Used: False | Specialised Paradigms: []
  Match_All_5: MISMATCH

--------------------------------------------------------------------------------------------------------------
RE-TEST RESULTS (compact summary)
--------------------------------------------------------------------------------------------------------------
 Paper ID       Model GT_Foundational Paradigm New_Agent_Foundational Paradigm Match_Foundational Paradigm      GT_ML Learning Type New_Agent_ML Learning Type Match_ML Learning Type                   GT_ML Problem Type New_Agent_ML Problem Type Match_ML Problem Type GT_Deep Learning Used New_Agent_Deep Learning Used Match_Deep Learning Used                                           GT_Specialised Paradigms                                    New_Agent_Specialised Paradigms Match_Specialised Paradigms Match_All_5
 2020 - 8 gpt-4o-mini         Machine Learning                Machine Learning                       MATCH             unsupervised               unsupervised                  MATCH clustering; dimensionality reduction                clustering              MISMATCH                 False                        False                    MATCH                      Natural Language Processing; Network Analysis                                        Natural Language Processing                    MISMATCH    MISMATCH
2021 - 56 gpt-4o-mini                    Mixed                           Mixed                       MATCH supervised; unsupervised                 supervised               MISMATCH               clustering; regression                regression              MISMATCH                 False                        False                    MATCH                 Natural Language Processing; Time-Series Analytics                 Natural Language Processing; Time-Series Analytics                       MATCH    MISMATCH
2023 - 58 gpt-4o-mini         Machine Learning                           Mixed                    MISMATCH             unsupervised               unsupervised                  MATCH                           clustering                clustering                 MATCH                 False                        False                    MATCH Emerging Paradigms; Natural Language Processing; Spatial Analytics Emerging Paradigms; Natural Language Processing; Spatial Analytics                       MATCH    MISMATCH
2024 - 99 gpt-4o-mini         Machine Learning                Machine Learning                       MATCH               supervised                         []               MISMATCH                  reward optimisation                        []              MISMATCH                 False                        False                    MATCH                           Spatial Analytics; Time-Series Analytics                                                                 []                    MISMATCH    MISMATCH

# Inspection

In [7]:
# Optional: inspect detailed reasoning for one rerun paper
if "retest_df" in globals() and len(retest_df):
    example_pid = "2023 - 58"
    show_iteration_reasoning(retest_df, example_pid, show_bibliography=True)
else:
    print("retest_df not found. Run the Iteration 1 cell first.")

retest_df not found. Run the Iteration 1 cell first.

In [10]:
run_modelling_iteration(
    paper_ids= ['2021 - 56'], # Enter Paper ID HERE. 
    llm_model="gpt-4o-mini",
    verbose=True,
    include_reasoning=True,
    show_reasoning_in_logs=True,
    log_bibliography=True
)

Re-running modelling node for 2021 - 56 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Mixed | ML Learning Type: supervised; unsupervised | ML Problem Type: clustering; regression | Deep Learning Used: False | Specialised Paradigms: Natural Language Processing; Time-Series Analytics
  Match_All_5: MATCH

====================================================================================================
PAPER: 2021 - 56 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Mixed
  Agent : Mixed
  Match : MATCH

ML Learning Type
  GT    : supervised; unsupervised
  Agent : supervised; unsupervised
  Match : MATCH

ML Problem Type
  GT    : clustering; regression
  Agent : clustering; regression
  Match : MATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : Natural Language Processing; Time-Series Analytics
  Agent : Natural Language Processing; Time-Series Analytics
  Match : MATCH

Overall all-5-dimensions match: MATCH
Confidence: 0.9
Overall validated reasoning:
  The study employs both classical statistical models (e.g., ARIMA) and machine learning models (e.g., XGBoost)
  within the same research design, indicating a mixed approach. The presence of traditional models for
  comparison with machine learning models further supports this classification [1][8]. The primary focus is on
  predicting hotel demand using supervised learning with XGBoost for regression tasks. However, the mention of
  hierarchical clustering indicates the use of unsupervised learning for segmentation, which is valid in this
  context. The study explicitly employs text mining techniques on social media data to enhance hotel demand
  forecasts, indicating the use of Natural Language Processing. Additionally, the mention of forecasting models,
  including improvements over ARIMA and the use of XGBoost for demand forecasting, indicates the presence of
  Time-Series Analytics.
Audit commentary:
  (none)
Bibliography:
  [1] page=1 | section=Abstract
      quote: This study aims to predict hotel demand through text analysis by investigating keyword series to increase
             demand predictions ' precision. To do so, this paper presents a framework for modeling hotel demand that
             incorporates machine learning techniques.
  [2] page=1 | section=Abstract
      quote: the empirical forecasting is conducted by introducing a segmented machine learning approach of leveraging
             hierarchical clustering tied to machine learning and deep learning techniques.
  [3] page=9 | section=Data and methodology
      quote: To derive the clusters for the segmented XGBoost model, we leverage hierarchical clustering in the resort ' s
             PMS data.
  [4] page=7 | section=Data and methodology
      quote: Using common revenue management metrics, we also assessed each model ' s forecasts based on their performance
             with 4 forecast horizons on rooms occupied of 1 day, 4 days, 7 days and 14 days, all applied to the OOT
             sample.
  [5] page=9 | section=Data and methodology
      quote: the segmented learning approach improved the forecasts ' stability and robustness while mitigating common
             overfitting issues within a highly dimensional data set.
  [6] page=9 | section=Data and methodology
      quote: the model was trained and validated using the training data set and the validation data set was split from the
             training data set.
  [7] page=6 | section=Data and methodology
      quote: the machine learning XGBoost model showed a 70% improvement over the ARIMA in the MAPE when used on a 1-day
             and a 30% improvement in the MAPE on a 14-day horizon.
  [8] page=5 | section=Forecasting models
      quote: we adopt a combination of basic forecasting models and machine learning techniques. We start by introducing a
             naïve model, followed by a traditional ARIMA model, before encoding an advanced machine learning model, the
             XGBoost, to predict hotel occupancy.
  [9] page=2 | section=
      quote: this study introduces a modeling framework for incorporating text mining via deep learning techniques on
             qualitative social media data to improve hotel demand forecasts
  [10] page=2 | section=
      quote: the segmented learning approach improved the forecasts' stability and robustness while mitigating common
             overfitting issues within a highly dimensional data set

--------------------------------------------------------------------------------------------------------------
RE-TEST RESULTS (compact summary)
--------------------------------------------------------------------------------------------------------------
 Paper ID       Model GT_Foundational Paradigm New_Agent_Foundational Paradigm Match_Foundational Paradigm      GT_ML Learning Type New_Agent_ML Learning Type Match_ML Learning Type     GT_ML Problem Type New_Agent_ML Problem Type Match_ML Problem Type GT_Deep Learning Used New_Agent_Deep Learning Used Match_Deep Learning Used                           GT_Specialised Paradigms                    New_Agent_Specialised Paradigms Match_Specialised Paradigms Match_All_5
2021 - 56 gpt-4o-mini                    Mixed                           Mixed                       MATCH supervised; unsupervised   supervised; unsupervised                  MATCH clustering; regression    clustering; regression                 MATCH                 False                        False                    MATCH Natural Language Processing; Time-Series Analytics Natural Language Processing; Time-Series Analytics                       MATCH       MATCH

,Paper ID,Model,GT_Foundational Paradigm,New_Agent_Foundational Paradigm,Match_Foundational Paradigm,GT_ML Learning Type,New_Agent_ML Learning Type,Match_ML Learning Type,GT_ML Problem Type,New_Agent_ML Problem Type,...,Match_Deep Learning Used,GT_Specialised Paradigms,New_Agent_Specialised Paradigms,Match_Specialised Paradigms,overall_validated_reasoning,audit_commentary,confidence,validated_bibliography_count,validated_bibliography_lines,Match_All_5
0,2021 - 56,gpt-4o-mini,Mixed,Mixed,MATCH,supervised; unsupervised,supervised; unsupervised,MATCH,clustering; regression,clustering; regression,...,MATCH,Natural Language Processing; Time-Series Analy...,Natural Language Processing; Time-Series Analy...,MATCH,The study employs both classical statistical m...,,0.9,10,"[[1] page=1 | section=Abstract, quote: Thi...",MATCH

# Re-run on All Included Papers

In [8]:
all_papers = comparison_df["Paper ID"].tolist()
print(f'length of all papers: {len(all_papers)}')
all_papers

length of all papers: 7

['2018 - 8',
 '2019 - 33',
 '2020 - 8',
 '2021 - 28',
 '2021 - 56',
 '2023 - 58',
 '2024 - 99']

In [10]:
full_retest = run_modelling_iteration(
    paper_ids= all_papers,  
    llm_model="gpt-4o-mini",
    verbose=True,
    include_reasoning=True,
    show_reasoning_in_logs=True,
    log_bibliography=True
)
full_retest

Re-running modelling node for 2018 - 8 with gpt-4o-mini...

C:\Users\sahil\OneDrive\PhD\3. Empirical Study\Methodological Workflow\utils\paper_retriever.py:9: LangChainDeprecationWarning: The class `Chroma` was deprecated in LangChain 0.2.9 and will be removed in 1.0. An updated version of the class exists in the `langchain-chroma package and should be used instead. To use it run `pip install -U `langchain-chroma` and import as `from `langchain_chroma import Chroma``.
  self._vectorstore = Chroma(

  Assigned labels -> Foundational Paradigm: Mixed | ML Learning Type: supervised | ML Problem Type: regression | Deep Learning Used: False | Specialised Paradigms: []
  Match_All_5: MISMATCH

====================================================================================================
PAPER: 2018 - 8 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Mixed
  Agent : Mixed
  Match : MATCH

ML Learning Type
  GT    : supervised
  Agent : supervised
  Match : MATCH

ML Problem Type
  GT    : classification; regression
  Agent : regression
  Match : MISMATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : []
  Agent : []
  Match : MATCH

Overall all-5-dimensions match: MISMATCH
Confidence: 1.0
Overall validated reasoning:
  The foundational paradigm is classified as Mixed, as the study employs both classical statistical models
  (Lasso regression) and machine learning models (Random Forest) in a two-stage modeling approach. The evidence
  supports the classification of both methodologies under supervised learning, as they are used to model
  outcomes based on labeled data. The regression problem type is validated by the explicit mention of Lasso for
  modeling and Random Forest for predicting outcomes. There are no specialised paradigms identified in the
  evidence, as the methodologies discussed do not involve specialized analytical methods fitting into defined
  paradigms. The confidence remains high as the evidence is comprehensive and consistent across the layers.
Audit commentary:
  No inconsistencies were found across the layers. The foundational paradigm, machine learning type, problem
  type, and absence of specialised paradigms are all logically consistent with the evidence provided.
Bibliography:
  [1] page=4 | section=3. Methodology
      quote: Following the reasoning of two-stage models, two methodologies will be applied in each stage: regression model
             with Lasso (Least Absolute Shrinkage and Selection Operator) penalty (Lasso) and Random Forest (RF).
  [2] page=5 | section=3.1. Application
      quote: In the first stage, it is modeled the probability of spending and in the second stage the strictly positive
             total expenditure is modeled. Lasso and RF methodologies are applied in both stages.
  [3] page=5 | section=3.1. Application
      quote: For the implementation of the models mentioned above, the original sample is partitioned into a training
             sample and a test sample.
  [4] page=5 | section=3.1. Application
      quote: The analysis of the predictive performance of the models (applied through a training sample and a test sample)
             shows that Random Forest method has the greater predictive capacity.
  [5] page=4 | section=3. Methodology
      quote: Random Forest will be applied by combining n trees based on n boostrap samples.
  [6] page=4 | section=3. Methodology
      quote: The two-step model presents an innovation when using Lasso to perform regression and model selection at the
             same time.
  [7] page=5 | section=3.1. Application
      quote: In the first step (Classification Step) a Logit model with Lasso is constructed to obtain a model for the
             probability that a tourist will spend or not.
  [8] page=5 | section=3.1. Application
      quote: In second stage (Regression Step), a regression model with Lasso is applied to estimate the average value of
             the total expenditure per capita.
  [9] page=6 | section=5. Conclusions and future research
      quote: the methodologies are innovative, in the sense that they are techniques framed within Machine Learning.
  [10] page=6 | section=5. Conclusions and future research
      quote: the analysis of the predictive performance of the models (applied through a training sample and a test sample)
             shows that Random Forest method has the greater predictive capacity.
Re-running modelling node for 2019 - 33 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Classical Statistical Modelling | ML Learning Type: [] | ML Problem Type: [] | Deep Learning Used: False | Specialised Paradigms: []
  Match_All_5: MATCH

====================================================================================================
PAPER: 2019 - 33 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Classical Statistical Modelling
  Agent : Classical Statistical Modelling
  Match : MATCH

ML Learning Type
  GT    : []
  Agent : []
  Match : MATCH

ML Problem Type
  GT    : []
  Agent : []
  Match : MATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : []
  Agent : []
  Match : MATCH

Overall all-5-dimensions match: MATCH
Confidence: 0.9
Overall validated reasoning:
  The study employs conventional statistical tests such as the Welch two samples t-test and the Mann-Whitney-
  Wilcoxon Test, which are indicative of hypothesis-driven modelling and focus on inference about data-
  generating processes. Additionally, the use of nonparametric kernel density estimators for testing differences
  further supports this classification, as it aligns with the characteristics of classical statistical
  modelling, which includes strong parametric assumptions and a focus on interpretability of results [1][2]. No
  specialized paradigms were identified as the methodologies discussed do not align with established paradigms
  such as Natural Language Processing.
Audit commentary:
  No inconsistencies were found across the layers. The foundational paradigm is appropriately classified as
  Classical Statistical Modelling, with no machine learning components present, and no specialized paradigms
  identified due to the nature of the methods employed.
Bibliography:
  [1] page=2 | section=Methodology
      quote: To compare ORs, we employed both conventional (Welch two samples t-test) and non-parametric (Mann-Whitney-
             Wilcoxon Test) statistical tests.
  [2] page=2 | section=Methodology
      quote: We employed nonparametric kernel density estimators to test if the sub-distribution of mobile OR ratings was
             significantly different from that of desktop ORs.
  [3] page=2 | section=Mobile online reviews
      quote: We analyse over 1.2 million online reviews from Booking.com and detect the presence and distinctive features
             of online reviews submitted by mobile devices.
  [4] page=2 | section=Mobile online reviews
      quote: Specifically, we used the Tn-statistic proposed by Li, Maasoumi, and Racine (2009) and tests reported in
             Maasoumi and Racine (2002) to test if the sub-distribution was equal.
Re-running modelling node for 2020 - 8 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Machine Learning | ML Learning Type: unsupervised | ML Problem Type: clustering | Deep Learning Used: False | Specialised Paradigms: Natural Language Processing; Network Analysis
  Match_All_5: MISMATCH

====================================================================================================
PAPER: 2020 - 8 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Machine Learning
  Agent : Machine Learning
  Match : MATCH

ML Learning Type
  GT    : unsupervised
  Agent : unsupervised
  Match : MATCH

ML Problem Type
  GT    : clustering; dimensionality reduction
  Agent : clustering
  Match : MISMATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : Natural Language Processing; Network Analysis
  Agent : Natural Language Processing; Network Analysis
  Match : MATCH

Overall all-5-dimensions match: MISMATCH
Confidence: 1.0
Overall validated reasoning:
  The study employs Latent Dirichlet Allocation (LDA) and Latent Semantic Indexing (LSI), which are algorithms
  used for topic modeling. These methods focus on discovering patterns in data (specifically, text collections)
  and are characterized by minimal distributional assumptions and a goal of predictive performance, aligning
  with the characteristics of Machine Learning [2]. The use of a stochastic algorithm and the emphasis on
  extracting latent topics further supports this classification, as it indicates a focus on pattern discovery
  rather than hypothesis testing or inference [1][3]. The application of topic modeling using LDA and LSI
  classifies it as Unsupervised Learning, and the task of identifying latent topics aligns with the problem type
  of clustering [1][2][3]. Additionally, the study employs topic modeling techniques such as LDA and LSI, which
  are indicative of Natural Language Processing. Furthermore, it applies network science methods to analyze
  digital ecosystems, indicating the use of Network Analysis [6][7][8].
Audit commentary:
  (none)
Bibliography:
  [1] page=6 | section=JHTT
      quote: We then applied a stochastic algorithm for topic modeling.
  [2] page=6 | section=JHTT
      quote: Among the many possible modelling algorithms, we chose the Latent Dirichlet allocation (LDA) and Latent
             Semantic Indexing (LSI).
  [3] page=6 | section=JHTT
      quote: The LDA is a generative statistical model for ensembles of discrete data (e.g. text collections).
  [4] page=6 | section=JHTT
      quote: It uses a hierarchical Bayesian model to extract the latent, or hidden, topics present in a collection of
             documents.
  [5] page=6 | section=JHTT
      quote: LSI is an indexing method based on a mathematical technique called singular value decomposition (SVD).
  [6] page=1 | section=Abstract
      quote: A content analysis of recent relevant literature is performed with the help of machine learning topic
             modelling algorithms.
  [7] page=5 | section=3. Materials and methods
      quote: Section 3.2 applies the methods of network science to identify the effects of a technological layer to the
             overall efficiency of the smart tourism system.
  [8] page=9 | section=4.2 Network-based analytical approach
      quote: The study applies a network analytic approach to digital ecosystems.
Re-running modelling node for 2021 - 28 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Mixed | ML Learning Type: supervised | ML Problem Type: regression | Deep Learning Used: False | Specialised Paradigms: []
  Match_All_5: MATCH

====================================================================================================
PAPER: 2021 - 28 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Mixed
  Agent : Mixed
  Match : MATCH

ML Learning Type
  GT    : supervised
  Agent : supervised
  Match : MATCH

ML Problem Type
  GT    : regression
  Agent : regression
  Match : MATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : []
  Agent : []
  Match : MATCH

Overall all-5-dimensions match: MATCH
Confidence: 0.8
Overall validated reasoning:
  The foundational paradigm is classified as Mixed due to the use of both classical statistical methods (Fama-
  MacBeth regressions) and machine learning methods (Elastic Net). The Elastic Net is a supervised learning
  method used for regression tasks, which justifies the classification of ml_learning_type as 'supervised' and
  ml_problem_type as 'regression'. There is no evidence supporting the inclusion of any specialised paradigms as
  the study does not involve temporal, textual, spatial, relational, or multimedia data processing. The
  confidence is slightly reduced due to the absence of specialised paradigms, but the core classifications
  remain valid.
Audit commentary:
  The classifications are logically consistent across the layers, and the reasoning aligns with the evidence
  provided. The absence of specialised paradigms is justified based on the nature of the methods used.
Bibliography:
  [1] page=4 | section=4. Methods
      quote: We examine the statistical importance of particular characteristics with Fama-MacBeth (FM) regressions (1973,
             FM hereafter). This two-step procedure is commonly used in cross-sectional research and eliminates problems of
             heteroskedasticity and autocorrelation.
  [2] page=5 | section=4. Methods
      quote: We use a machine learning tool called 'Elastic net' that eliminates the weights of the least critical features
             (Zou & Hastie, 2005).
  [3] page=5 | section=4. Methods
      quote: Finally, in the last step, we run the multivariate FM regressions that simultaneously consider all important
             variables.
Re-running modelling node for 2021 - 56 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Mixed | ML Learning Type: supervised; unsupervised | ML Problem Type: clustering; regression | Deep Learning Used: False | Specialised Paradigms: Natural Language Processing; Time-Series Analytics
  Match_All_5: MATCH

====================================================================================================
PAPER: 2021 - 56 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Mixed
  Agent : Mixed
  Match : MATCH

ML Learning Type
  GT    : supervised; unsupervised
  Agent : supervised; unsupervised
  Match : MATCH

ML Problem Type
  GT    : clustering; regression
  Agent : clustering; regression
  Match : MATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : Natural Language Processing; Time-Series Analytics
  Agent : Natural Language Processing; Time-Series Analytics
  Match : MATCH

Overall all-5-dimensions match: MATCH
Confidence: 1.0
Overall validated reasoning:
  The foundational paradigm is classified as Mixed, which supports the presence of both supervised and
  unsupervised learning types. The evidence indicates that hierarchical clustering is used for segmentation
  (unsupervised) and XGBoost for regression (supervised), thus validating both learning types and associated
  problem types. Furthermore, the study employs text mining techniques for qualitative analysis, confirming the
  use of Natural Language Processing, and utilizes forecasting models including ARIMA for predicting hotel
  demand, aligning with Time-Series Analytics. All classifications are consistent with the evidence presented
  [1][2][3][6][7][10].
Audit commentary:
  (none)
Bibliography:
  [1] page=1 | section=Abstract
      quote: this paper presents a framework for modeling hotel demand that incorporates machine learning techniques.
  [2] page=1 | section=Abstract
      quote: the empirical forecasting is conducted by introducing a segmented machine learning approach of leveraging
             hierarchical clustering tied to machine learning and deep learning techniques.
  [3] page=9 | section=Data and methodology
      quote: To derive the clusters for the segmented XGBoost model, we leverage hierarchical clustering in the resort's
             PMS data.
  [4] page=9 | section=Data and methodology
      quote: We started with summarizing booking curves, seasonal patterns and daily distributions of booked rooms for each
             custom attribute.
  [5] page=9 | section=Data and methodology
      quote: Next, we standardized each attribute's metrics and introduced them into the median algorithm's hierarchical
             clustering.
  [6] page=9 | section=Data and methodology
      quote: With the clusters set, we returned the parameter inputs from the XGBoost model before summarizing each
             segment-based forecast into a final segmented XGBoost forecast.
  [7] page=6 | section=IJCHM
      quote: the machine learning XGBoost model showed a 70% improvement over the ARIMA in the MAPE when used on a 1-day
             and a 30% improvement in the MAPE on a 14-day horizon.
  [8] page=7 | section=Data and methodology
      quote: For any that used a validation data set (e.g. machine learning) within their development, the validation data
             set was split from the training data set.
  [9] page=8 | section=Data and methodology
      quote: We assess variable importance in the learning algorithm via matrix importance plots.
  [10] page=8 | section=Data and methodology
      quote: We investigate the statistics of MAPE, RSME, MSE and MAD between the training data set and the validation data
             set to assess the overall model fit and generalization.
  [11] page=2 | section=Introduction
      quote: This study introduces a modeling framework for incorporating text mining via deep learning techniques on
             qualitative social media data to improve hotel demand forecasts in light of the aforementioned gaps.
  [12] page=5 | section=Forecasting models
      quote: We start by introducing a naïve model, followed by a traditional ARIMA model, before encoding an advanced
             machine learning model, the XGBoost, to predict hotel occupancy.
Re-running modelling node for 2023 - 58 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Machine Learning | ML Learning Type: unsupervised | ML Problem Type: clustering | Deep Learning Used: False | Specialised Paradigms: Emerging Paradigms; Natural Language Processing; Spatial Analytics
  Match_All_5: MATCH

====================================================================================================
PAPER: 2023 - 58 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Machine Learning
  Agent : Machine Learning
  Match : MATCH

ML Learning Type
  GT    : unsupervised
  Agent : unsupervised
  Match : MATCH

ML Problem Type
  GT    : clustering
  Agent : clustering
  Match : MATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : Emerging Paradigms; Natural Language Processing; Spatial Analytics
  Agent : Emerging Paradigms; Natural Language Processing; Spatial Analytics
  Match : MATCH

Overall all-5-dimensions match: MATCH
Confidence: 0.9
Overall validated reasoning:
  The study employs Latent Dirichlet Allocation (LDA) for topic modeling, which is a method associated with
  machine learning. The focus is on probabilistic distributions (gamma values) and performance improvement
  through hyperparameter tuning, indicating a predictive modeling goal rather than hypothesis testing or
  inference. The evaluation of the model based on posterior likelihood further aligns with machine learning
  characteristics, emphasizing predictive performance and model selection rather than traditional statistical
  diagnostics. Therefore, the foundational paradigm is classified as Machine Learning. The evidence provided
  indicates the use of topic modelling (LDA), which is classified as unsupervised learning. The direct quotes
  describe the application of LDA for analyzing photo topics and assigning probabilities to each photo, which
  aligns with the definition of unsupervised learning focused on discovering hidden patterns in unlabelled
  datasets. The evidence indicates that LDA (Latent Dirichlet Allocation) is used for topic modelling, which is
  classified as 'clustering' since it groups observations (photos) into categories based on their content. The
  assignment of photos to their most probable gaze based on the LDA model supports this classification.
  Additionally, the study employs topic modelling using LDA, which is a method of Natural Language Processing

,Paper ID,Model,GT_Foundational Paradigm,New_Agent_Foundational Paradigm,Match_Foundational Paradigm,GT_ML Learning Type,New_Agent_ML Learning Type,Match_ML Learning Type,GT_ML Problem Type,New_Agent_ML Problem Type,...,Match_Deep Learning Used,GT_Specialised Paradigms,New_Agent_Specialised Paradigms,Match_Specialised Paradigms,overall_validated_reasoning,audit_commentary,confidence,validated_bibliography_count,validated_bibliography_lines,Match_All_5
0,2018 - 8,gpt-4o-mini,Mixed,Mixed,MATCH,supervised,supervised,MATCH,classification; regression,regression,...,MATCH,[],[],MATCH,The foundational paradigm is classified as Mix...,No inconsistencies were found across the layer...,1.0,10,"[[1] page=4 | section=3. Methodology, quot...",MISMATCH
1,2019 - 33,gpt-4o-mini,Classical Statistical Modelling,Classical Statistical Modelling,MATCH,[],[],MATCH,[],[],...,MATCH,[],[],MATCH,The study employs conventional statistical tes...,No inconsistencies were found across the layer...,0.9,4,"[[1] page=2 | section=Methodology, quote: ...",MATCH
2,2020 - 8,gpt-4o-mini,Machine Learning,Machine Learning,MATCH,unsupervised,unsupervised,MATCH,clustering; dimensionality reduction,clustering,...,MATCH,Natural Language Processing; Network Analysis,Natural Language Processing; Network Analysis,MATCH,The study employs Latent Dirichlet Allocation ...,,1.0,8,"[[1] page=6 | section=JHTT, quote: We then...",MISMATCH
3,2021 - 28,gpt-4o-mini,Mixed,Mixed,MATCH,supervised,supervised,MATCH,regression,regression,...,MATCH,[],[],MATCH,The foundational paradigm is classified as Mix...,The classifications are logically consistent a...,0.8,3,"[[1] page=4 | section=4. Methods, quote: W...",MATCH
4,2021 - 56,gpt-4o-mini,Mixed,Mixed,MATCH,supervised; unsupervised,supervised; unsupervised,MATCH,clustering; regression,clustering; regression,...,MATCH,Natural Language Processing; Time-Series Analy...,Natural Language Processing; Time-Series Analy...,MATCH,The foundational paradigm is classified as Mix...,,1.0,12,"[[1] page=1 | section=Abstract, quote: thi...",MATCH
5,2023 - 58,gpt-4o-mini,Machine Learning,Machine Learning,MATCH,unsupervised,unsupervised,MATCH,clustering,clustering,...,MATCH,Emerging Paradigms; Natural Language Processin...,Emerging Paradigms; Natural Language Processin...,MATCH,The study employs Latent Dirichlet Allocation ...,,0.9,10,[[1] page=6 | section=3.2. Topic modelling (LD...,MATCH
6,2024 - 99,gpt-4o-mini,Machine Learning,Machine Learning,MATCH,optimization-based learning,optimization-based learning,MATCH,reward optimisation,reward optimisation,...,MATCH,[],[],MATCH,The evidence indicates that the OptiPres Model...,No specialised paradigms were identified in th...,0.8,3,[[1] page=6 | section=OptiPres Model Objective...,MATCH

#### Iteration 2: On Full Set

In [10]:
full_retest = run_modelling_iteration(
    paper_ids= all_papers,  
    llm_model="gpt-4o-mini",
    verbose=True,
    include_reasoning=True,
    show_reasoning_in_logs=True,
    log_bibliography=True
)
full_retest

Re-running modelling node for 2018 - 8 with gpt-4o-mini...

C:\Users\sahil\OneDrive\PhD\3. Empirical Study\Methodological Workflow\utils\paper_retriever.py:9: LangChainDeprecationWarning: The class `Chroma` was deprecated in LangChain 0.2.9 and will be removed in 1.0. An updated version of the class exists in the `langchain-chroma package and should be used instead. To use it run `pip install -U `langchain-chroma` and import as `from `langchain_chroma import Chroma``.
  self._vectorstore = Chroma(

  Assigned labels -> Foundational Paradigm: Mixed | ML Learning Type: supervised | ML Problem Type: classification; regression | Deep Learning Used: False | Specialised Paradigms: []
  Match_All_5: MATCH

====================================================================================================
PAPER: 2018 - 8 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Mixed
  Agent : Mixed
  Match : MATCH

ML Learning Type
  GT    : supervised
  Agent : supervised
  Match : MATCH

ML Problem Type
  GT    : classification; regression
  Agent : classification; regression
  Match : MATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : []
  Agent : []
  Match : MATCH

Overall all-5-dimensions match: MATCH
Confidence: 0.8
Overall validated reasoning:
  The foundational paradigm is classified as 'Mixed' since the study employs both classical statistical models
  (Lasso regression and Logit model) and machine learning models (Random Forest). The presence of a
  'Classification Step' indicates the use of logistic regression for predictive classification, while Random
  Forest is utilized for its predictive performance. The evidence supports the classification of both Lasso and
  Random Forest under supervised learning, as they are applied in classification and regression tasks. However,
  there are no specialized paradigms identified in the study, as the methodologies do not correspond to defined
  specialized paradigms in the DSRP framework. This results in a slight reduction in confidence due to the
  absence of specialized paradigms despite the strong support for the foundational and ML classifications.
  [1][3][4][6][7]
Audit commentary:
  The study's methodologies are well-supported, but the lack of specialized paradigms results in a lower
  confidence score. The evidence is robust for the foundational and ML classifications, but further
  clarification on the data types and their analysis would strengthen the validation.
Bibliography:
  [1] page=4 | section=3. Methodology
      quote: two methodologies will be applied in each stage: regression model with Lasso (Least Absolute Shrinkage and
             Selection Operator) penalty (Lasso) and Random Forest (RF).
  [2] page=4 | section=3. Methodology
      quote: As a second alternative methodology to apply in each stage, it is proposed Random Forest.
  [3] page=5 | section=3.1. Application
      quote: In the first step (Classification Step) a Logit model with Lasso is constructed to obtain a model for the
             probability that a tourist will spend or not.
  [4] page=5 | section=3.1. Application
      quote: In second stage (Regression Step), a regression model with Lasso is applied to estimate the average value of
             the total expenditure per capita.
  [5] page=5 | section=3.1. Application
      quote: For the RF application, it is based on the first stage in the combination of 500 classification trees (based
             on 500 bootstrap samples) and in the second stage in a similar way combining regression trees.
  [6] page=5 | section=4. Results
      quote: The analysis of the predictive performance of the models (applied through a training sample and a test sample)
             shows that Random Forest method has the greater predictive capacity.
  [7] page=4 | section=3. Methodology
      quote: The two-step model presents an innovation when using Lasso to perform regression and model selection at the
             same time.
Re-running modelling node for 2019 - 33 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Classical Statistical Modelling | ML Learning Type: [] | ML Problem Type: [] | Deep Learning Used: False | Specialised Paradigms: []
  Match_All_5: MATCH

====================================================================================================
PAPER: 2019 - 33 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Classical Statistical Modelling
  Agent : Classical Statistical Modelling
  Match : MATCH

ML Learning Type
  GT    : []
  Agent : []
  Match : MATCH

ML Problem Type
  GT    : []
  Agent : []
  Match : MATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : []
  Agent : []
  Match : MATCH

Overall all-5-dimensions match: MATCH
Confidence: 0.9
Overall validated reasoning:
  The foundational paradigm is validated as Classical Statistical Modelling due to the use of conventional
  statistical tests and nonparametric kernel density estimators that focus on inference about the data-
  generating process. There are no mentions of any specialised modelling paradigms in the evidence, which
  supports the absence of specialised paradigms in the analysis.
Audit commentary:
  The foundational paradigm is consistent with the evidence provided, which focuses on Classical Statistical
  Modelling through hypothesis testing. There are no specialised paradigms present in the study, and the absence
  of machine learning classifications is appropriate given the foundational paradigm.
Bibliography:
  [1] page=2 | section=2. Mobile online reviews
      quote: To compare ORs, we employed both conventional (Welch two samples t-test) and non-parametric (Mann-Whitney-
             Wilcoxon Test) statistical tests.
  [2] page=2 | section=2. Mobile online reviews
      quote: We employed nonparametric kernel density estimators to test if the sub-distribution of mobile OR ratings was
             significantly different from that of desktop ORs.
  [3] page=2 | section=4.2. Differences in mobile vs. desktop ORs
      quote: Specifically, we used the Tn-statistic proposed by Li, Maasoumi, and Racine (2009) and tests reported in
             Maasoumi and Racine (2002) to test if the sub-distribution was equal.
Re-running modelling node for 2020 - 8 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Machine Learning | ML Learning Type: unsupervised | ML Problem Type: clustering | Deep Learning Used: False | Specialised Paradigms: Natural Language Processing; Network Analysis
  Match_All_5: MATCH

====================================================================================================
PAPER: 2020 - 8 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Machine Learning
  Agent : Machine Learning
  Match : MATCH

ML Learning Type
  GT    : unsupervised
  Agent : unsupervised
  Match : MATCH

ML Problem Type
  GT    : clustering
  Agent : clustering
  Match : MATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : Natural Language Processing; Network Analysis
  Agent : Natural Language Processing; Network Analysis
  Match : MATCH

Overall all-5-dimensions match: MATCH
Confidence: 1.0
Overall validated reasoning:
  The foundational paradigm is validated as 'Machine Learning' due to the use of algorithms like LDA and LSI for
  topic modeling, which fall under unsupervised learning and clustering. The evidence supports the
  classification of the study's methods, emphasizing predictive modeling and pattern discovery without labeled
  outcomes. The specialised paradigms of 'Natural Language Processing' and 'Network Analysis' are confirmed as
  appropriate given the textual analysis and network analytic approaches employed in the study. All reasoning
  references align with the extracted evidence [1][2][5][6][8][9].
Audit commentary:
  The configurations across layers are consistent with the evidence provided, and all relevant paradigms are
  supported by the study's methodologies.
Bibliography:
  [1] page=6 | section=JHTT
      quote: We then applied a stochastic algorithm for topic modeling.
  [2] page=6 | section=JHTT
      quote: Among the many possible modelling algorithms, we chose the Latent Dirichlet allocation (LDA) and Latent
             Semantic Indexing (LSI) as they are consistently mentioned as the most reliable.
  [3] page=6 | section=JHTT
      quote: The LDA is a generative statistical model for ensembles of discrete data (e.g. text collections).
  [4] page=10 | section=JHTT
      quote: Main (top 15) topics with their main components (top 10 words) discovered with the Latent Dirichlet allocation
             and Latent Semantic Indexing algorithms.
  [5] page=1 | section=Abstract
      quote: A content analysis of recent relevant literature is performed with the help of machine learning topic
             modelling algorithms.
  [6] page=9 | section=4.1 Content analysis
      quote: the analysis employs textual analysis techniques, implemented through scripts using the Natural Language Tool
             Kit (Bird et al., 2009), Gensim and Scikit-learn Python packages.
  [7] page=9 | section=4.1 Content analysis
      quote: we derived a frequency distribution for words and 2-grams (contiguous sequences of two words).
  [8] page=1 | section=Abstract
      quote: a network analytic approach to digital ecosystems, then, is used to study the relationship between
             technological tools and physical entities in a destination.
  [9] page=5 | section=3. Materials and methods
      quote: Section 3.2 applies the methods of network science to identify the effects of a technological layer to the
             overall efficiency of the smart tourism system.
Re-running modelling node for 2021 - 28 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Mixed | ML Learning Type: supervised | ML Problem Type: [] | Deep Learning Used: False | Specialised Paradigms: []
  Match_All_5: MISMATCH

====================================================================================================
PAPER: 2021 - 28 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Mixed
  Agent : Mixed
  Match : MATCH

ML Learning Type
  GT    : supervised
  Agent : supervised
  Match : MATCH

ML Problem Type
  GT    : regression
  Agent : []
  Match : MISMATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : []
  Agent : []
  Match : MATCH

Overall all-5-dimensions match: MISMATCH
Confidence: 0.9
Overall validated reasoning:
  The study employs both classical statistical modelling, as evidenced by the use of Fama-MacBeth regressions
  for examining statistical importance (id 1 and id 3), and machine learning methods, specifically the Elastic
  Net tool for feature selection (id 2). This combination of techniques indicates a mixed approach,
  incorporating both paradigms for complementary analysis. The use of 'Elastic net' indicates the application of
  supervised learning methods, as Elastic Net is a regression technique that combines penalties of both Lasso
  and Ridge regression to perform variable selection and regularization [2]. This aligns with the definition of
  supervised learning, where models are trained on labeled datasets. The presence of Fama-MacBeth regressions
  further supports the classification as it is commonly used in supervised contexts for regression analysis [1].
  However, the context does not indicate that Elastic Net is used for a specific machine learning problem type,
  resulting in no established ML problem type.
Audit commentary:
  The foundational paradigm is validated as mixed due to the presence of both classical and machine learning
  methods. The reasoning for ML learning type is supported, but no specific ML problem type was identified,
  which is consistent with the evidence provided.
Bibliography:
  [1] page=4 | section=Methods
      quote: We examine the statistical importance of particular characteristics with Fama-MacBeth (FM) regressions (1973,
             FM hereafter). This two-step procedure is commonly used in cross-sectional research and eliminates problems of
             heteroskedasticity and autocorrelation.
  [2] page=5 | section=Methods
      quote: Simultaneously, we verify each characteristic ' s importance from a different perspective and use a machine
             learning tool called ' Elastic net ' that eliminates the weights of the least critical features (Zou & Hastie,
             2005).
  [3] page=5 | section=Methods
      quote: In the last step, we run the multivariate FM regressions that simultaneously consider all important variables.
Re-running modelling node for 2021 - 56 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Mixed | ML Learning Type: supervised; unsupervised | ML Problem Type: clustering; regression | Deep Learning Used: False | Specialised Paradigms: Natural Language Processing; Time-Series Analytics
  Match_All_5: MATCH

====================================================================================================
PAPER: 2021 - 56 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Mixed
  Agent : Mixed
  Match : MATCH

ML Learning Type
  GT    : supervised; unsupervised
  Agent : supervised; unsupervised
  Match : MATCH

ML Problem Type
  GT    : clustering; regression
  Agent : clustering; regression
  Match : MATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : Natural Language Processing; Time-Series Analytics
  Agent : Natural Language Processing; Time-Series Analytics
  Match : MATCH

Overall all-5-dimensions match: MATCH
Confidence: 1.0
Overall validated reasoning:
  The study employs both classical statistical models (e.g., ARIMA) and machine learning techniques (e.g.,
  XGBoost, hierarchical clustering) within the same research design. The combination of basic forecasting models
  and advanced machine learning approaches indicates a mixed methodology, fulfilling the criteria for
  classification as Mixed [1][2][3][9][10]. Furthermore, the use of XGBoost for predictive modeling classifies
  as supervised learning due to its application in forecasting hotel occupancy [3][10]. Additionally,
  hierarchical clustering is utilized to segment the data, which is a hallmark of unsupervised learning [2][4].
  There is no evidence of deep learning architectures being employed in the methods described. The evidence
  indicates that the study involves predicting hotel occupancy using the XGBoost model, which is a regression
  technique, and hierarchical clustering is explicitly mentioned as a method used to segment the data,
  classifying it as a clustering problem type. Therefore, both 'regression' and 'clustering' are valid
  classifications based on the provided evidence. The study also employs text mining and sentiment analysis on
  social media data, which are indicative of Natural Language Processing (NLP) [1][5]. Additionally, it includes
  forecasting models like ARIMA and XGBoost, which are used for predicting hotel demand over time, thus
  indicating Time-Series Analytics [8][10].
Audit commentary:
  (none)
Bibliography:
  [1] page=1 | section=Abstract
      quote: To do so, this paper presents a framework for modeling hotel demand that incorporates machine learning
             techniques.
  [2] page=1 | section=Abstract
      quote: the empirical forecasting is conducted by introducing a segmented machine learning approach of leveraging
             hierarchical clustering tied to machine learning and deep learning techniques.
  [3] page=5 | section=Forecasting models
      quote: we adopt a combination of basic forecasting models and machine learning techniques. We start by introducing a
             naïve model, followed by a traditional ARIMA model, before encoding an advanced machine learning model, the
             XGBoost, to predict hotel occupancy.
  [4] page=9 | section=Data and methodology
      quote: we leverage hierarchical clustering in the resort ' s PMS data.
  [5] page=9 | section=Data and methodology
      quote: To assess the ideal number of clusters, we used a combination of the explanatory statistics of semi-partial R
             2 , the median distance between clusters and the cubic clustering criterion.
  [6] page=9 | section=Data and methodology
      quote: we then returned the parameter inputs from the XGBoost model before summarizing each segment-based forecast
             into a final segmented XGBoost forecast.
  [7] page=8 | section=Data and methodology
      quote: we limit the trees ' depths and cross-validations to minimize overfitting issues.
  [8] page=8 | section=Data and methodology
      quote: we assess variable importance in the learning algorithm via matrix importance plots.
  [9] page=7 | section=Data and methodology
      quote: Using common revenue management metrics, we also assessed each model ' s forecasts based on their performance
             with 4 forecast horizons on rooms occupied of 1 day, 4 days, 7 days and 14 days, all applied to the OOT
             sample.
  [10] page=6 | section=Data and methodology
      quote: the machine learning XGBoost model showed a 70% improvement over the ARIMA in the MAPE when used on a 1-day
             and a 30% improvement in the MAPE on a 14-day horizon.
  [11] page=2 | section=
      quote: this study introduces a modeling framework for incorporating text mining via deep learning techniques on
             qualitative social media data to improve hotel demand forecasts
  [12] page=9 | section=Data and methodology
      quote: we conducted a sentiment analysis on the longitudinal social media data.
  [13] page=1 | section=Abstract
      quote: the machine learning XGBoost model showed a 70% improvement over the ARIMA in the MAPE when used on a 1-day
             and a 30% improvement in the MAPE on a 14-day horizon.
  [14] page=5 | section=Forecasting models
      quote: we adopt a combination of basic forecasting models and machine learning techniques.
  [15] page=5 | section=Forecasting models
      quote: we start by introducing a naïve model, followed by a traditional ARIMA model, before encoding an advanced
             machine learning model, the XGBoost, to predict hotel occupancy.
Re-running modelling node for 2023 - 58 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Machine Learning | ML Learning Type: unsupervised | ML Problem Type: clustering | Deep Learning Used: False | Specialised Paradigms: Emerging Paradigms; Natural Language Processing; Spatial Analytics
  Match_All_5: MATCH

====================================================================================================
PAPER: 2023 - 58 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Machine Learning
  Agent : Machine Learning
  Match : MATCH

ML Learning Type
  GT    : unsupervised
  Agent : unsupervised
  Match : MATCH

ML Problem Type
  GT    : clustering
  Agent : clustering
  Match : MATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : Emerging Paradigms; Natural Language Processing; Spatial Analytics
  Agent : Emerging Paradigms; Natural Language Processing; Spatial Analytics
  Match : MATCH

Overall all-5-dimensions match: MATCH
Confidence: 1.0
Overall validated reasoning:
  The foundational paradigm is classified as Machine Learning, which is consistent with the use of Latent
  Dirichlet Allocation (LDA) for topic modeling, classified under unsupervised learning and clustering. The
  study does not employ any deep learning architectures. The specialised paradigms of Natural Language
  Processing, Spatial Analytics, and Emerging Paradigms are supported by the evidence regarding LDA, spatial

,Paper ID,Model,GT_Foundational Paradigm,New_Agent_Foundational Paradigm,Match_Foundational Paradigm,GT_ML Learning Type,New_Agent_ML Learning Type,Match_ML Learning Type,GT_ML Problem Type,New_Agent_ML Problem Type,...,Match_Deep Learning Used,GT_Specialised Paradigms,New_Agent_Specialised Paradigms,Match_Specialised Paradigms,overall_validated_reasoning,audit_commentary,confidence,validated_bibliography_count,validated_bibliography_lines,Match_All_5
0,2018 - 8,gpt-4o-mini,Mixed,Mixed,MATCH,supervised,supervised,MATCH,classification; regression,classification; regression,...,MATCH,[],[],MATCH,The foundational paradigm is classified as 'Mi...,"The study's methodologies are well-supported, ...",0.8,7,"[[1] page=4 | section=3. Methodology, quot...",MATCH
1,2019 - 33,gpt-4o-mini,Classical Statistical Modelling,Classical Statistical Modelling,MATCH,[],[],MATCH,[],[],...,MATCH,[],[],MATCH,The foundational paradigm is validated as Clas...,The foundational paradigm is consistent with t...,0.9,3,[[1] page=2 | section=2. Mobile online reviews...,MATCH
2,2020 - 8,gpt-4o-mini,Machine Learning,Machine Learning,MATCH,unsupervised,unsupervised,MATCH,clustering,clustering,...,MATCH,Natural Language Processing; Network Analysis,Natural Language Processing; Network Analysis,MATCH,The foundational paradigm is validated as 'Mac...,The configurations across layers are consisten...,1.0,9,"[[1] page=6 | section=JHTT, quote: We then...",MATCH
3,2021 - 28,gpt-4o-mini,Mixed,Mixed,MATCH,supervised,supervised,MATCH,regression,[],...,MATCH,[],[],MATCH,The study employs both classical statistical m...,The foundational paradigm is validated as mixe...,0.9,3,"[[1] page=4 | section=Methods, quote: We e...",MISMATCH
4,2021 - 56,gpt-4o-mini,Mixed,Mixed,MATCH,supervised; unsupervised,supervised; unsupervised,MATCH,clustering; regression,clustering; regression,...,MATCH,Natural Language Processing; Time-Series Analy...,Natural Language Processing; Time-Series Analy...,MATCH,The study employs both classical statistical m...,,1.0,15,"[[1] page=1 | section=Abstract, quote: To ...",MATCH
5,2023 - 58,gpt-4o-mini,Machine Learning,Machine Learning,MATCH,unsupervised,unsupervised,MATCH,clustering,clustering,...,MATCH,Emerging Paradigms; Natural Language Processin...,Emerging Paradigms; Natural Language Processin...,MATCH,The foundational paradigm is classified as Mac...,,1.0,6,[[1] page=6 | section=3.2. Topic modelling (LD...,MATCH
6,2024 - 99,gpt-4o-mini,Machine Learning,Machine Learning,MATCH,optimization-based learning,optimization-based learning,MATCH,reward optimisation,reward optimisation,...,MATCH,[],[],MATCH,The foundational paradigm is validated as Mach...,The foundational model's classification is con...,0.8,4,[[1] page=6 | section=OptiPres Model Objective...,MATCH

#### Iteration 3: On Full Set (re-testing)

In [13]:
full_retest = run_modelling_iteration(
    paper_ids= all_papers,  
    llm_model="gpt-4o-mini",
    verbose=True,
    include_reasoning=True,
    show_reasoning_in_logs=True,
    log_bibliography=True
)
full_retest

Re-running modelling node for 2018 - 8 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Mixed | ML Learning Type: supervised | ML Problem Type: classification; regression | Deep Learning Used: False | Specialised Paradigms: []
  Match_All_5: MATCH

====================================================================================================
PAPER: 2018 - 8 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Mixed
  Agent : Mixed
  Match : MATCH

ML Learning Type
  GT    : supervised
  Agent : supervised
  Match : MATCH

ML Problem Type
  GT    : classification; regression
  Agent : classification; regression
  Match : MATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : []
  Agent : []
  Match : MATCH

Overall all-5-dimensions match: MATCH
Confidence: 0.9
Overall validated reasoning:
  The study employs both classical statistical models and machine learning models. It utilizes a Logit model
  with Lasso penalty for classification, which indicates a classical statistical approach focused on inference
  and probability estimation related to tourist spending. Simultaneously, it applies Random Forest, a machine
  learning method, for prediction, emphasizing predictive performance and validation through a test sample. The
  combination of these two methodologies in the same research design aligns with the Mixed paradigm, as it
  integrates both statistical inference and predictive modeling techniques. The evidence indicates the use of
  supervised learning methods, specifically regression models with Lasso and Random Forest, which are both
  classified under supervised learning. The Logit model with Lasso is also used for predicting the probability
  of a tourist's spending behavior, confirming the supervised nature of the learning type. The study explicitly
  describes a 'Classification Step' where a Logit model is constructed to predict the probability that a tourist
  will spend or not, which clearly indicates a classification problem type. Additionally, the use of a
  regression model with Lasso penalty also indicates a regression problem type. The presence of Random Forest as
  both a classification and regression method further supports the classification of both types. However, no
  specialised paradigms were found as the study does not model temporal dynamics, textual data, geospatial
  relationships, or relational data structures that would classify it under any of the specialised paradigms
  defined.
Audit commentary:
  (none)
Bibliography:
  [1] page=4 | section=3. Methodology
      quote: Following the reasoning of two-stage models, two methodologies will be applied in each stage: regression model
             with Lasso (Least Absolute Shrinkage and Selection Operator) penalty (Lasso) and Random Forest (RF).
  [2] page=4 | section=3. Methodology
      quote: As a second alternative methodology to apply in each stage, it is proposed Random Forest.
  [3] page=5 | section=3.1. Application
      quote: In the first step (Classification Step) a Logit model with Lasso is constructed to obtain a model for the
             probability that a tourist will spend or not.
  [4] page=5 | section=3.1. Application
      quote: For the RF application, it is based on the first stage in the combination of 500 classification trees (based
             on 500 bootstrap samples) and in the second stage in a similar way combining regression trees.
  [5] page=5 | section=4. Results
      quote: Models are estimated with the training sample, and with the test sample the prediction error of the models is
             evaluated, that is, the validation of the model will be carried out from a new set of data, different from
             those obtained with the model.
Re-running modelling node for 2019 - 33 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Classical Statistical Modelling | ML Learning Type: [] | ML Problem Type: [] | Deep Learning Used: False | Specialised Paradigms: []
  Match_All_5: MATCH

====================================================================================================
PAPER: 2019 - 33 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Classical Statistical Modelling
  Agent : Classical Statistical Modelling
  Match : MATCH

ML Learning Type
  GT    : []
  Agent : []
  Match : MATCH

ML Problem Type
  GT    : []
  Agent : []
  Match : MATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : []
  Agent : []
  Match : MATCH

Overall all-5-dimensions match: MATCH
Confidence: 0.9
Overall validated reasoning:
  The study employs conventional statistical tests such as the Welch two samples t-test and the Mann-Whitney-
  Wilcoxon Test, which are indicative of hypothesis-driven modelling and focus on inference about the data-
  generating process. These methods align with the characteristics of Classical Statistical Modelling, including
  strong parametric assumptions and statistical diagnostics [1, 2]. No specialised paradigms were identified in
  the study as the methods applied do not correspond to any of the specified modelling paradigms.
Audit commentary:
  Validated foundational paradigm as Classical Statistical Modelling based on the use of conventional
  statistical tests. No ML details are applicable as the foundational paradigm is not Machine Learning or Mixed.
  No specialised paradigms were identified in the study as the methods applied do not correspond to any of the
  specified modelling paradigms.
Bibliography:
  [1] page=2 | section=Methodology
      quote: To compare ORs, we employed both conventional (Welch two samples t-test) and non-parametric (Mann-Whitney-
             Wilcoxon Test) statistical tests.
  [2] page=2 | section=Methodology
      quote: We employed nonparametric kernel density estimators to test if the sub-distribution of mobile OR ratings was
             significantly different from that of desktop ORs.
  [3] page=2 | section=4.2. Differences in mobile vs. desktop ORs
      quote: Specifically, we used the Tn-statistic proposed by Li, Maasoumi, and Racine (2009) and tests reported in
             Maasoumi and Racine (2002) to test if the sub-distribution was equal.
Re-running modelling node for 2020 - 8 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Machine Learning | ML Learning Type: unsupervised | ML Problem Type: clustering | Deep Learning Used: False | Specialised Paradigms: Natural Language Processing; Network Analysis
  Match_All_5: MATCH

====================================================================================================
PAPER: 2020 - 8 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Machine Learning
  Agent : Machine Learning
  Match : MATCH

ML Learning Type
  GT    : unsupervised
  Agent : unsupervised
  Match : MATCH

ML Problem Type
  GT    : clustering
  Agent : clustering
  Match : MATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : Natural Language Processing; Network Analysis
  Agent : Natural Language Processing; Network Analysis
  Match : MATCH

Overall all-5-dimensions match: MATCH
Confidence: 0.9
Overall validated reasoning:
  The study employs topic modeling techniques such as Latent Dirichlet Allocation (LDA) and Latent Semantic
  Indexing (LSI), which are algorithmic approaches focused on pattern discovery from data, aligning with the
  characteristics of Machine Learning. The mention of a 'stochastic algorithm' and the generative nature of LDA
  indicates a focus on predictive modeling and pattern discovery rather than hypothesis testing or parameter
  interpretation typical of Classical Statistical Modelling. The absence of hypothesis testing or statistical
  diagnostics further supports this classification [1][2][3]. The use of LDA and LSI confirms the classification
  as unsupervised learning methods focused on discovering hidden patterns in unlabelled datasets, specifically
  for clustering topics without labeled outcomes. Additionally, the study employs methods indicative of Natural
  Language Processing, such as topic modeling using LDA and LSI, which are specialized techniques for analyzing
  textual data. The application of network science methods indicates the use of Network Analysis to assess
  relationships within the smart tourism system [6][7][8].
Audit commentary:
  (none)
Bibliography:
  [1] page=6 | section=JHTT
      quote: We then applied a stochastic algorithm for topic modeling. Among the many possible modelling algorithms, we
             chose the Latent Dirichlet allocation (LDA) and Latent Semantic Indexing (LSI) as they are consistently
             mentioned as the most reliable.
  [2] page=6 | section=JHTT
      quote: The LDA is a generative statistical model for ensembles of discrete data (e.g. text collections). It uses a
             hierarchical Bayesian model to extract the latent, or hidden, topics present in a collection of documents.
  [3] page=10 | section=JHTT
      quote: Table 3. Main (top 15) topics with their main components (top 10 words) discovered with the Latent Dirichlet
             allocation and Latent Semantic Indexing algorithms.
  [4] page=1 | section=Abstract
      quote: A content analysis of recent relevant literature is performed with the help of machine learning topic
             modelling algorithms.
  [5] page=5 | section=3. Materials and methods
      quote: Section 3.2 applies the methods of network science to identify the effects of a technological layer to the
             overall efficiency of the smart tourism system.
  [6] page=9 | section=4.2 Network-based analytical approach
      quote: To improve in absorptive capacities an effective process re-engineering within intra and inter-organizational
             groups needs to be put in place.
Re-running modelling node for 2021 - 28 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Mixed | ML Learning Type: supervised | ML Problem Type: [] | Deep Learning Used: False | Specialised Paradigms: []
  Match_All_5: MISMATCH

====================================================================================================
PAPER: 2021 - 28 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Mixed
  Agent : Mixed
  Match : MATCH

ML Learning Type
  GT    : supervised
  Agent : supervised
  Match : MATCH

ML Problem Type
  GT    : regression
  Agent : []
  Match : MISMATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : []
  Agent : []
  Match : MATCH

Overall all-5-dimensions match: MISMATCH
Confidence: 0.9
Overall validated reasoning:
  The foundational paradigm is classified as 'Mixed' due to the use of both classical statistical methods (Fama-
  MacBeth regressions) and machine learning methods (Elastic Net). The machine learning type is 'Supervised
  Learning' based on the application of Elastic Net for feature importance assessment. However, the problem type
  is classified as empty because the evidence does not specify a clear machine learning problem. The absence of
  specialised paradigms is validated, as no evidence supports the use of time-series analytics, natural language
  processing, spatial analytics, network analysis, or emerging paradigms.
Audit commentary:
  The foundational paradigm classification as 'Mixed' is validated based on the presence of both classical
  statistical and machine learning methods. The machine learning type is correctly identified as 'Supervised
  Learning', while the problem type is deemed empty due to insufficient evidence. The reasoning is well
  supported by the cited evidence.
Bibliography:
  [1] page=4 | section=4. Methods
      quote: We examine the statistical importance of particular characteristics with Fama-MacBeth (FM) regressions (1973,
             FM hereafter). This twostep procedure is commonly used in cross-sectional research and eliminates problems of
             heteroskedasticity and autocorrelation.
  [2] page=5 | section=4. Methods
      quote: Simultaneously, we verify each characteristic ' s importance from a different perspective and use a machine
             learning tool called ' Elastic net ' that eliminates the weights of the least critical features (Zou & Hastie,
             2005).
  [3] page=5 | section=4. Methods
      quote: Finally, in the last step, we run the multivariate FM regressions that simultaneously consider all important
             variables.
Re-running modelling node for 2021 - 56 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Mixed | ML Learning Type: supervised; unsupervised | ML Problem Type: clustering; regression | Deep Learning Used: False | Specialised Paradigms: Natural Language Processing; Time-Series Analytics
  Match_All_5: MATCH

====================================================================================================
PAPER: 2021 - 56 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Mixed
  Agent : Mixed
  Match : MATCH

ML Learning Type
  GT    : supervised; unsupervised
  Agent : supervised; unsupervised
  Match : MATCH

ML Problem Type
  GT    : clustering; regression
  Agent : clustering; regression
  Match : MATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : Natural Language Processing; Time-Series Analytics
  Agent : Natural Language Processing; Time-Series Analytics
  Match : MATCH

Overall all-5-dimensions match: MATCH
Confidence: 1.0
Overall validated reasoning:
  The study employs both classical statistical methods (ARIMA model) and machine learning techniques (XGBoost,
  hierarchical clustering, etc.) to model hotel demand and predict occupancy. The presence of both traditional
  and advanced machine learning models indicates a mixed approach, as evidenced by the use of different methods
  for comparison and assessment of model performance [1][2][10]. The modelling evidence indicates the use of
  machine learning techniques, specifically mentioning the XGBoost model which is typically used for regression
  tasks (predicting hotel occupancy) [2]. Additionally, hierarchical clustering is explicitly used to segment
  rooms into homogeneous clusters, which classifies it as unsupervised learning [4]. The combination of these
  two types of analysis supports the classification as both 'regression' and 'clustering'. Furthermore, the
  study incorporates text mining techniques on social media data to improve hotel demand forecasts, indicating
  the use of Natural Language Processing [1]. Additionally, the study utilizes time-series forecasting models
  such as ARIMA and XGBoost for demand forecasting, which indicates the application of Time-Series Analytics
  [10].
Audit commentary:
  (none)
Bibliography:
  [1] page=2 | section=
      quote: this study introduces a modeling framework for incorporating text mining via deep learning techniques on
             qualitative social media data to improve hotel demand forecasts
  [2] page=1 | section=Abstract
      quote: this paper presents a framework for modeling hotel demand that incorporates machine learning techniques
  [3] page=2 | section=
      quote: empirical forecasting was conducted by introducing a segmented approach based on hierarchical clustering tied
             to machine learning techniques
  [4] page=8 | section=Data and methodology
      quote: the learning algorithm is applied at the macro level as daily occupied rooms
  [5] page=9 | section=
      quote: the sentiment-based variables are then added as an independent input to the XGBoost model
  [6] page=9 | section=
      quote: the machine learning XGBoost model showed a 70% improvement over the ARIMA in the MAPE
  [7] page=5 | section=Forecasting models
      quote: we adopt a combination of basic forecasting models and machine learning techniques
  [8] page=19 | section=
      quote: the segmented learning approach mitigates the negative effects of market shifts
  [9] page=9 | section=
      quote: we assess variable importance in the learning algorithm via matrix importance plots
  [10] page=2 | section=
      quote: the analysis employs various models including the moving average (MA), the autoregressive integrated moving
             average (ARIMA) and the gradient boosting framework (XGBoost)
Re-running modelling node for 2023 - 58 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Machine Learning | ML Learning Type: unsupervised | ML Problem Type: clustering | Deep Learning Used: False | Specialised Paradigms: Emerging Paradigms; Natural Language Processing; Spatial Analytics
  Match_All_5: MATCH

====================================================================================================
PAPER: 2023 - 58 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Machine Learning
  Agent : Machine Learning
  Match : MATCH

ML Learning Type
  GT    : unsupervised
  Agent : unsupervised
  Match : MATCH

ML Problem Type
  GT    : clustering
  Agent : clustering
  Match : MATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : Emerging Paradigms; Natural Language Processing; Spatial Analytics
  Agent : Emerging Paradigms; Natural Language Processing; Spatial Analytics
  Match : MATCH

Overall all-5-dimensions match: MATCH
Confidence: 0.9
Overall validated reasoning:
  The foundational paradigm is consistent with the use of Latent Dirichlet Allocation (LDA) for topic modeling,
  which is a characteristic of unsupervised learning. The study's focus on clustering tourist gazes aligns with
  the unsupervised learning classification. The specialised paradigms are also validated; Natural Language
  Processing corresponds to the textual data analysis through LDA, Spatial Analytics pertains to the spatial
  analysis of user regions, and Emerging Paradigms relate to the visual content analysis of photographs.
Audit commentary:
  (none)
Bibliography:
  [1] page=6 | section=3.2. Topic modelling (LDA)
      quote: To perform LDA, the authors first indicated the number of topics (gazes).
  [2] page=6 | section=3.2. Topic modelling (LDA)
      quote: LDA was performed with 5 random starts and the best model was selected on the bases of the highest posterior
             likelihood.
  [3] page=6 | section=3.2. Topic modelling (LDA)
      quote: The LDA model also produces gamma values -a probability distribution over topics -of each photo.
  [4] page=6 | section=3.3. Analyses of the tourist gazes
      quote: To analyse the gazes of tourists, photos were separated on the basis of the user ' s region of residence.
  [5] page=8 | section=4.1. Twelve gazes identified by LDA
      quote: The study classifies tourist gazes into three tourist categories: the North-American Western gaze, the
             European-Western gaze and the Asian gaze.
  [6] page=6 | section=3.3. Analyses of the tourist gazes
      quote: A spatial analysis was performed to illustrate the associations between user's region and locations in
             Bangkok.
  [7] page=7 | section=3.4. Visual content analysis (VCA) of the tourist gaze
      quote: Photographs taken by international tourists were systematically selected for further VCA which is a

,Paper ID,Model,GT_Foundational Paradigm,New_Agent_Foundational Paradigm,Match_Foundational Paradigm,GT_ML Learning Type,New_Agent_ML Learning Type,Match_ML Learning Type,GT_ML Problem Type,New_Agent_ML Problem Type,...,Match_Deep Learning Used,GT_Specialised Paradigms,New_Agent_Specialised Paradigms,Match_Specialised Paradigms,overall_validated_reasoning,audit_commentary,confidence,validated_bibliography_count,validated_bibliography_lines,Match_All_5
0,2018 - 8,gpt-4o-mini,Mixed,Mixed,MATCH,supervised,supervised,MATCH,classification; regression,classification; regression,...,MATCH,[],[],MATCH,The study employs both classical statistical m...,,0.9,5,"[[1] page=4 | section=3. Methodology, quot...",MATCH
1,2019 - 33,gpt-4o-mini,Classical Statistical Modelling,Classical Statistical Modelling,MATCH,[],[],MATCH,[],[],...,MATCH,[],[],MATCH,The study employs conventional statistical tes...,Validated foundational paradigm as Classical S...,0.9,3,"[[1] page=2 | section=Methodology, quote: ...",MATCH
2,2020 - 8,gpt-4o-mini,Machine Learning,Machine Learning,MATCH,unsupervised,unsupervised,MATCH,clustering,clustering,...,MATCH,Natural Language Processing; Network Analysis,Natural Language Processing; Network Analysis,MATCH,The study employs topic modeling techniques su...,,0.9,6,"[[1] page=6 | section=JHTT, quote: We then...",MATCH
3,2021 - 28,gpt-4o-mini,Mixed,Mixed,MATCH,supervised,supervised,MATCH,regression,[],...,MATCH,[],[],MATCH,The foundational paradigm is classified as 'Mi...,The foundational paradigm classification as 'M...,0.9,3,"[[1] page=4 | section=4. Methods, quote: W...",MISMATCH
4,2021 - 56,gpt-4o-mini,Mixed,Mixed,MATCH,supervised; unsupervised,supervised; unsupervised,MATCH,clustering; regression,clustering; regression,...,MATCH,Natural Language Processing; Time-Series Analy...,Natural Language Processing; Time-Series Analy...,MATCH,The study employs both classical statistical m...,,1.0,10,"[[1] page=2 | section=, quote: this study ...",MATCH
5,2023 - 58,gpt-4o-mini,Machine Learning,Machine Learning,MATCH,unsupervised,unsupervised,MATCH,clustering,clustering,...,MATCH,Emerging Paradigms; Natural Language Processin...,Emerging Paradigms; Natural Language Processin...,MATCH,The foundational paradigm is consistent with t...,,0.9,7,[[1] page=6 | section=3.2. Topic modelling (LD...,MATCH
6,2024 - 99,gpt-4o-mini,Machine Learning,Machine Learning,MATCH,optimization-based learning,optimization-based learning,MATCH,reward optimisation,reward optimisation,...,MATCH,[],[],MATCH,The study employs simulated annealing as part ...,All classifications and reasoning are consiste...,1.0,2,[[1] page=6 | section=OptiPres Model Objective...,MATCH

#### Iteration 4: On Full Set (After regression label fix)

In [17]:
full_retest = run_modelling_iteration(
    paper_ids= all_papers,  
    llm_model="gpt-4o-mini",
    verbose=True,
    include_reasoning=True,
    show_reasoning_in_logs=True,
    log_bibliography=True
)
full_retest

Re-running modelling node for 2018 - 8 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Mixed | ML Learning Type: supervised | ML Problem Type: classification; regression | Deep Learning Used: False | Specialised Paradigms: []
  Match_All_5: MATCH

====================================================================================================
PAPER: 2018 - 8 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Mixed
  Agent : Mixed
  Match : MATCH

ML Learning Type
  GT    : supervised
  Agent : supervised
  Match : MATCH

ML Problem Type
  GT    : classification; regression
  Agent : classification; regression
  Match : MATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : []
  Agent : []
  Match : MATCH

Overall all-5-dimensions match: MATCH
Confidence: 0.8
Overall validated reasoning:
  The foundational paradigm is classified as Mixed, as the study employs both classical statistical models
  (Logit with Lasso and regression with Lasso) and machine learning models (Random Forest). The learning type is
  validated as supervised due to the use of labeled datasets in both classification and regression tasks. The
  problem types of classification and regression are supported by explicit references to a 'Classification Step'
  and a regression model for expenditure estimation. However, the absence of specialised paradigms suggests that
  while the methodologies are valid, they do not fit into specific analytical frameworks such as time-series or
  spatial analytics [1][2][3][4][5][6][8].
Audit commentary:
  The study does not provide evidence of the application of any specialised paradigms, focusing solely on
  regression and machine learning methods.
Bibliography:
  [1] page=4 | section=3. Methodology
      quote: Following the reasoning of two-stage models, two methodologies will be applied in each stage: regression model
             with Lasso (Least Absolute Shrinkage and Selection Operator) penalty (Lasso) and Random Forest (RF).
  [2] page=5 | section=3.1. Application
      quote: In the first step (Classification Step) a Logit model with Lasso is constructed to obtain a model for the
             probability that a tourist will spend or not.
  [3] page=5 | section=3.1. Application
      quote: In second stage (Regression Step), a regression model with Lasso is applied to estimate the average value of
             the total expenditure per capita.
  [4] page=4 | section=3. Methodology
      quote: As a second alternative methodology to apply in each stage, it is proposed Random Forest.
  [5] page=5 | section=3.1. Application
      quote: For the RF application, it is based on the first stage in the combination of 500 classification trees (based
             on 500 bootstrap samples) and in the second stage in a similar way combining regression trees.
  [6] page=6 | section=5. Conclusions and future research
      quote: The methodologies are innovative, in the sense that they are techniques framed within Machine Learning. In
             particular, CART and RF are non-classical models that are usually used in problems where ≤ p n and where no a
             priori assumption is needed.
  [7] page=4 | section=3. Methodology
      quote: The optimization algorithm depends on an implicit parameter, which we denote as λ, considered the penalty
             factor. As λ grows the amount of variables that the model will take as significant will be greater (less
             contraction).
  [8] page=5 | section=4. Results
      quote: For the implementation of the models mentioned above, the original sample is partitioned into a training
             sample and a test sample.
Re-running modelling node for 2019 - 33 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Classical Statistical Modelling | ML Learning Type: [] | ML Problem Type: [] | Deep Learning Used: False | Specialised Paradigms: []
  Match_All_5: MATCH

====================================================================================================
PAPER: 2019 - 33 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Classical Statistical Modelling
  Agent : Classical Statistical Modelling
  Match : MATCH

ML Learning Type
  GT    : []
  Agent : []
  Match : MATCH

ML Problem Type
  GT    : []
  Agent : []
  Match : MATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : []
  Agent : []
  Match : MATCH

Overall all-5-dimensions match: MATCH
Confidence: 0.9
Overall validated reasoning:
  The study employs conventional statistical tests such as the Welch two samples t-test and the Mann-Whitney-
  Wilcoxon Test, which are indicative of hypothesis-driven modelling and focus on inference about the data-
  generating process. These methods align with the characteristics of Classical Statistical Modelling, including
  strong parametric assumptions and evaluation through statistical diagnostics [1][2]. The evidence provided
  indicates the use of statistical tests and kernel density estimators, but does not indicate the use of any
  specialised modelling paradigms such as Time-Series Analytics, Natural Language Processing, Spatial Analytics,
  Network Analysis, or Emerging Paradigms.
Audit commentary:
  The study's methodology does not support any specialised modelling paradigms as defined in the validation
  criteria. All evidence pertains to statistical tests rather than the specified paradigms.
Bibliography:
  [1] page=2 | section=Methodology
      quote: To compare ORs, we employed both conventional (Welch two samples t-test) and non-parametric (Mann-Whitney-
             Wilcoxon Test) statistical tests.
  [2] page=2 | section=Methodology
      quote: We employed nonparametric kernel density estimators to test if the sub-distribution of mobile OR ratings was
             significantly different from that of desktop ORs.
  [3] page=2 | section=4.2. Differences in mobile vs. desktop ORs
      quote: Specifically, we used the Tn-statistic proposed by Li, Maasoumi, and Racine (2009) and tests reported in
             Maasoumi and Racine (2002) to test if the sub-distribution was equal.
Re-running modelling node for 2020 - 8 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Machine Learning | ML Learning Type: unsupervised | ML Problem Type: clustering | Deep Learning Used: False | Specialised Paradigms: Natural Language Processing; Network Analysis
  Match_All_5: MATCH

====================================================================================================
PAPER: 2020 - 8 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Machine Learning
  Agent : Machine Learning
  Match : MATCH

ML Learning Type
  GT    : unsupervised
  Agent : unsupervised
  Match : MATCH

ML Problem Type
  GT    : clustering
  Agent : clustering
  Match : MATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : Natural Language Processing; Network Analysis
  Agent : Natural Language Processing; Network Analysis
  Match : MATCH

Overall all-5-dimensions match: MATCH
Confidence: 1.0
Overall validated reasoning:
  The study applies machine learning topic modeling algorithms, specifically Latent Dirichlet Allocation (LDA)
  and Latent Semantic Indexing (LSI), which are algorithmic approaches focused on predictive performance and
  pattern discovery from data. The use of terms like 'stochastic algorithm for topic modeling' and 'machine
  learning topic modelling algorithms' indicates a strong emphasis on prediction and pattern discovery rather
  than hypothesis testing or inference, which are characteristic of classical statistical modeling [1][2][5].
  The evidence provided indicates the use of topic modeling algorithms, specifically Latent Dirichlet Allocation
  (LDA) and Latent Semantic Indexing (LSI), which are classified under unsupervised learning as they discover
  hidden patterns in unlabelled datasets. The direct quotes confirm the application of these methods in the
  study, supporting the classification as unsupervised learning [1][2][3][4][5]. The evidence indicates the use
  of topic modeling algorithms such as Latent Dirichlet Allocation (LDA) and Latent Semantic Indexing (LSI),
  which are typically categorized under clustering methods as they aim to discover groups of similar
  observations (topics) within the data. This aligns with the definition of clustering, where the goal is to
  segment data into homogeneous groups without labeled outcomes. The references explicitly mention the
  application of these algorithms for modeling topics, which supports the classification as clustering.
  Additionally, the study applies network science methods, which suggests the presence of Network Analysis as a
  specialized paradigm, validated by evidence [7][8].
Audit commentary:
  (none)
Bibliography:
  [1] page=6 | section=JHTT
      quote: We then applied a stochastic algorithm for topic modeling.
  [2] page=6 | section=JHTT
      quote: Among the many possible modelling algorithms, we chose the Latent Dirichlet allocation (LDA) and Latent
             Semantic Indexing (LSI).
  [3] page=6 | section=JHTT
      quote: The LDA is a generative statistical model for ensembles of discrete data (e.g. text collections).
  [4] page=10 | section=JHTT
      quote: Main (top 15) topics with their main components (top 10 words) discovered with the Latent Dirichlet allocation
             and Latent Semantic Indexing algorithms.
  [5] page=1 | section=Abstract
      quote: A content analysis of recent relevant literature is performed with the help of machine learning topic
             modelling algorithms.
  [6] page=5 | section=3. Materials and methods
      quote: Section 3.2 applies the methods of network science to identify the effects of a technological layer to the
             overall efficiency of the smart tourism system.
  [7] page=9 | section=4.2 Network-based analytical approach
      quote: To improve in absorptive capacities an effective process re-engineering within intra and inter-organizational
             groups needs to be put in place.
Re-running modelling node for 2021 - 28 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Mixed | ML Learning Type: supervised | ML Problem Type: regression | Deep Learning Used: False | Specialised Paradigms: []
  Match_All_5: MATCH

====================================================================================================
PAPER: 2021 - 28 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Mixed
  Agent : Mixed
  Match : MATCH

ML Learning Type
  GT    : supervised
  Agent : supervised
  Match : MATCH

ML Problem Type
  GT    : regression
  Agent : regression
  Match : MATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : []
  Agent : []
  Match : MATCH

Overall all-5-dimensions match: MATCH
Confidence: 0.9
Overall validated reasoning:
  The foundational paradigm is classified as 'Mixed' because the study employs both classical statistical
  modelling (Fama-MacBeth regressions) and machine learning (Elastic Net) methods. The use of Elastic Net
  indicates a supervised learning type, as it is a machine learning tool for feature selection and prediction,
  and the study explicitly predicts a continuous dependent variable, the stock weekly log-return, which aligns
  with regression. There are no specialised paradigms identified as the study does not reference temporal,
  textual, geospatial, relational, or multimedia data analysis.
Audit commentary:
  The classifications across layers are logically consistent. The foundational paradigm supports the identified
  machine learning type and problem type. No specialised paradigms were found, which aligns with the evidence
  provided.
Bibliography:
  [1] page=4 | section=4. Methods
      quote: we apply normalization for all data used in Elastic net regression.
  [2] page=4 | section=4. Methods
      quote: we employ a two-stage procedure that preselects variables before implementing the final FM regression.
  [3] page=5 | section=4. Methods
      quote: we use a machine learning tool called 'Elastic net' that eliminates the weights of the least critical
             features.
  [4] page=5 | section=4. Methods
      quote: we run single-interaction FM regressions to define every single feature's statistical importance.
  [5] page=5 | section=4. Methods
      quote: we run the multivariate FM regressions that simultaneously consider all important variables.
  [6] page=9 | section=6. Conclusions
      quote: The dependent variable is the stock weekly log-return.
  [7] page=2 | section=A B S T R A C T
      quote: We use a machine learning tool Elastic net and Fama-MacBeth regressions.
Re-running modelling node for 2021 - 56 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Mixed | ML Learning Type: supervised; unsupervised | ML Problem Type: clustering | Deep Learning Used: False | Specialised Paradigms: Natural Language Processing; Time-Series Analytics
  Match_All_5: MISMATCH

====================================================================================================
PAPER: 2021 - 56 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Mixed
  Agent : Mixed
  Match : MATCH

ML Learning Type
  GT    : supervised; unsupervised
  Agent : supervised; unsupervised
  Match : MATCH

ML Problem Type
  GT    : clustering; regression
  Agent : clustering
  Match : MISMATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : Natural Language Processing; Time-Series Analytics
  Agent : Natural Language Processing; Time-Series Analytics
  Match : MATCH

Overall all-5-dimensions match: MISMATCH
Confidence: 1.0
Overall validated reasoning:
  The study employs both supervised learning (XGBoost) and unsupervised learning (hierarchical clustering), thus
  validating the mixed classification. The presence of hierarchical clustering indicates a clustering problem
  type. The use of machine learning techniques and model evaluation metrics supports the classification as
  Mixed. Additionally, the study incorporates text mining techniques for qualitative social media data analysis,
  indicating Natural Language Processing, and mentions forecasting models, including XGBoost and ARIMA,
  confirming a focus on Time-Series Analytics.
Audit commentary:
  The foundational paradigm was correctly identified as Mixed based on the use of both supervised and
  unsupervised learning methods. The reasoning is well-supported by the evidence provided in the bibliography.
  The inclusion of specialised paradigms is also justified by the evidence supporting Natural Language
  Processing and Time-Series Analytics.
Bibliography:
  [1] page=1 | section=Abstract
      quote: This study presents a framework for modeling hotel demand that incorporates machine learning techniques.
  [2] page=1 | section=Abstract
      quote: The empirical forecasting is conducted by introducing a segmented machine learning approach of leveraging
             hierarchical clustering tied to machine learning and deep learning techniques.
  [3] page=9 | section=Data and methodology
      quote: The rooms in the PMS data were segmented into homogenous clusters within the initial learning algorithms.
  [4] page=9 | section=Data and methodology
      quote: To derive the clusters for the segmented XGBoost model, we leverage hierarchical clustering in the resort ' s
             PMS data.
  [5] page=6 | section=Machine learning models
      quote: One such learning algorithm that has gained traction is XGBoost, introduced by Chen and Guestrin (2016).
  [6] page=5 | section=Forecasting models
      quote: we adopt a combination of basic forecasting models and machine learning techniques.
  [7] page=7 | section=Data and methodology
      quote: For any that used a validation data set (e.g. machine learning) within their development, the validation data
             set was split from the training data set.
  [8] page=16 | section=Practical implications
      quote: The segmented XGBoost model helps correct the residuals in the forecast with limited precision.
  [9] page=16 | section=Practical implications
      quote: The ability to be more robust to market deviations will allow hospitality organizations to segmented machine
             learning forecasts with longer lifecycles to minimize development time.
  [10] page=15 | section=Summarized results
      quote: The DM tests show that all machine learning algorithms improved the forecasts at an a = 0.05 level over the
             ARIMA and the Naïve forecasts for all time horizons.
  [11] page=18 | section=Data and methodology
      quote: We investigate the statistics of MAPE, RSME, MSE and MAD between the training data set and the validation data
             set to assess the overall model fit and generalization.
  [12] page=2 | section=
      quote: this study introduces a modeling framework for incorporating text mining via deep learning techniques on
             qualitative social media data to improve hotel demand forecasts
  [13] page=9 | section=Data and methodology
      quote: the sentiment-based variables are then added as an independent input to the XGBoost model.
  [14] page=16 | section=Practical implications
      quote: the machine learning XGBoost model showed a 70% improvement over the ARIMA in the MAPE when used on a 1-day
             and a 30% improvement in the MAPE on a 14-day horizon.
Re-running modelling node for 2023 - 58 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Machine Learning | ML Learning Type: unsupervised | ML Problem Type: clustering | Deep Learning Used: False | Specialised Paradigms: Emerging Paradigms; Natural Language Processing; Spatial Analytics
  Match_All_5: MATCH

====================================================================================================
PAPER: 2023 - 58 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Machine Learning
  Agent : Machine Learning
  Match : MATCH

ML Learning Type
  GT    : unsupervised
  Agent : unsupervised
  Match : MATCH

ML Problem Type
  GT    : clustering
  Agent : clustering
  Match : MATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : Emerging Paradigms; Natural Language Processing; Spatial Analytics
  Agent : Emerging Paradigms; Natural Language Processing; Spatial Analytics
  Match : MATCH

Overall all-5-dimensions match: MATCH
Confidence: 1.0
Overall validated reasoning:
  The study employs Latent Dirichlet Allocation (LDA), which is a method used for topic modeling, confirming the
  use of unsupervised learning for clustering. Furthermore, it supports the classifications of Natural Language
  Processing for analyzing textual data, Spatial Analytics for geospatial relationships, and Emerging Paradigms
  for visual content analysis. The evidence provided is comprehensive and directly supports the classifications
  across all layers [1][2][3][4][5][6][7][8][9][10][11][12][13].
Audit commentary:
  (none)
Bibliography:
  [1] page=6 | section=3.2. Topic modelling (LDA)
      quote: The tourist gazes of Bangkok were extracted from the photos using LDA.

,Paper ID,Model,GT_Foundational Paradigm,New_Agent_Foundational Paradigm,Match_Foundational Paradigm,GT_ML Learning Type,New_Agent_ML Learning Type,Match_ML Learning Type,GT_ML Problem Type,New_Agent_ML Problem Type,...,Match_Deep Learning Used,GT_Specialised Paradigms,New_Agent_Specialised Paradigms,Match_Specialised Paradigms,overall_validated_reasoning,audit_commentary,confidence,validated_bibliography_count,validated_bibliography_lines,Match_All_5
0,2018 - 8,gpt-4o-mini,Mixed,Mixed,MATCH,supervised,supervised,MATCH,classification; regression,classification; regression,...,MATCH,[],[],MATCH,The foundational paradigm is classified as Mix...,The study does not provide evidence of the app...,0.8,8,"[[1] page=4 | section=3. Methodology, quot...",MATCH
1,2019 - 33,gpt-4o-mini,Classical Statistical Modelling,Classical Statistical Modelling,MATCH,[],[],MATCH,[],[],...,MATCH,[],[],MATCH,The study employs conventional statistical tes...,The study's methodology does not support any s...,0.9,3,"[[1] page=2 | section=Methodology, quote: ...",MATCH
2,2020 - 8,gpt-4o-mini,Machine Learning,Machine Learning,MATCH,unsupervised,unsupervised,MATCH,clustering,clustering,...,MATCH,Natural Language Processing; Network Analysis,Natural Language Processing; Network Analysis,MATCH,The study applies machine learning topic model...,,1.0,7,"[[1] page=6 | section=JHTT, quote: We then...",MATCH
3,2021 - 28,gpt-4o-mini,Mixed,Mixed,MATCH,supervised,supervised,MATCH,regression,regression,...,MATCH,[],[],MATCH,The foundational paradigm is classified as 'Mi...,The classifications across layers are logicall...,0.9,7,"[[1] page=4 | section=4. Methods, quote: w...",MATCH
4,2021 - 56,gpt-4o-mini,Mixed,Mixed,MATCH,supervised; unsupervised,supervised; unsupervised,MATCH,clustering; regression,clustering,...,MATCH,Natural Language Processing; Time-Series Analy...,Natural Language Processing; Time-Series Analy...,MATCH,The study employs both supervised learning (XG...,The foundational paradigm was correctly identi...,1.0,14,"[[1] page=1 | section=Abstract, quote: Thi...",MISMATCH
5,2023 - 58,gpt-4o-mini,Machine Learning,Machine Learning,MATCH,unsupervised,unsupervised,MATCH,clustering,clustering,...,MATCH,Emerging Paradigms; Natural Language Processin...,Emerging Paradigms; Natural Language Processin...,MATCH,The study employs Latent Dirichlet Allocation ...,,1.0,13,[[1] page=6 | section=3.2. Topic modelling (LD...,MATCH
6,2024 - 99,gpt-4o-mini,Machine Learning,Machine Learning,MATCH,optimization-based learning,optimization-based learning,MATCH,reward optimisation,reward optimisation,...,MATCH,[],[],MATCH,The study employs a decision-analytic model th...,No specialised paradigms were found applicable...,0.9,3,[[1] page=5 | section=Optimization Preservatio...,MATCH

In [14]:
# Optional: inspect detailed reasoning for one rerun paper
if "full_retest" in globals() and len(full_retest):
    example_pid = "2021 - 28"
    show_iteration_reasoning(full_retest, example_pid, show_bibliography=True)

====================================================================================================
PAPER: 2021 - 28 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Mixed
  Agent : Mixed
  Match : MATCH

ML Learning Type
  GT    : supervised
  Agent : supervised
  Match : MATCH

ML Problem Type
  GT    : regression
  Agent : []
  Match : MISMATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : []
  Agent : []
  Match : MATCH

Overall all-5-dimensions match: MISMATCH
Confidence: 0.9
Overall validated reasoning:
  The foundational paradigm is classified as 'Mixed' due to the use of both classical statistical methods (Fama-
  MacBeth regressions) and machine learning methods (Elastic Net). The machine learning type is 'Supervised
  Learning' based on the application of Elastic Net for feature importance assessment. However, the problem type
  is classified as empty because the evidence does not specify a clear machine learning problem. The absence of
  specialised paradigms is validated, as no evidence supports the use of time-series analytics, natural language
  processing, spatial analytics, network analysis, or emerging paradigms.
Audit commentary:
  The foundational paradigm classification as 'Mixed' is validated based on the presence of both classical
  statistical and machine learning methods. The machine learning type is correctly identified as 'Supervised
  Learning', while the problem type is deemed empty due to insufficient evidence. The reasoning is well
  supported by the cited evidence.
Bibliography:
  [1] page=4 | section=4. Methods
      quote: We examine the statistical importance of particular characteristics with Fama-MacBeth (FM) regressions (1973,
             FM hereafter). This twostep procedure is commonly used in cross-sectional research and eliminates problems of
             heteroskedasticity and autocorrelation.
  [2] page=5 | section=4. Methods
      quote: Simultaneously, we verify each characteristic ' s importance from a different perspective and use a machine
             learning tool called ' Elastic net ' that eliminates the weights of the least critical features (Zou & Hastie,
             2005).
  [3] page=5 | section=4. Methods
      quote: Finally, in the last step, we run the multivariate FM regressions that simultaneously consider all important
             variables.

In [15]:
run_modelling_iteration(
    paper_ids= ['2021 - 28'], # Enter Paper ID HERE. 
    llm_model="gpt-4o-mini",
    verbose=True,
    include_reasoning=True,
    show_reasoning_in_logs=True,
    log_bibliography=True
)

Re-running modelling node for 2021 - 28 with gpt-4o-mini...
  Assigned labels -> Foundational Paradigm: Mixed | ML Learning Type: supervised | ML Problem Type: regression | Deep Learning Used: False | Specialised Paradigms: []
  Match_All_5: MATCH

====================================================================================================
PAPER: 2021 - 28 | MODEL: gpt-4o-mini
====================================================================================================

Foundational Paradigm
  GT    : Mixed
  Agent : Mixed
  Match : MATCH

ML Learning Type
  GT    : supervised
  Agent : supervised
  Match : MATCH

ML Problem Type
  GT    : regression
  Agent : regression
  Match : MATCH

Deep Learning Used
  GT    : False
  Agent : False
  Match : MATCH

Specialised Paradigms
  GT    : []
  Agent : []
  Match : MATCH

Overall all-5-dimensions match: MATCH
Confidence: 0.9
Overall validated reasoning:
  The study employs both machine learning and classical statistical methods. Specifically, it uses Elastic Net,
  a machine learning tool aimed at feature selection and prediction, indicating a predictive modelling goal [1].
  Additionally, it examines the statistical importance of characteristics using Fama-MacBeth regressions, which
  are typical of classical statistical modelling focused on parameter interpretation and hypothesis testing
  [2][3]. The mention of the dependent variable being the stock weekly log-return suggests a continuous outcome
  prediction, further supporting the use of both paradigms [4]. Therefore, the study clearly fits into the
  'Mixed' category as it integrates both methodologies. The evidence indicates the use of a machine learning
  tool called 'Elastic net', which is a supervised learning method used for regression tasks, thus validating
  the classification of supervised learning and regression as the problem type.
Audit commentary:
  No specialised paradigms were found in the study as it did not reference any modelling approaches related to
  temporal, textual, geospatial, or relational graph paradigms.
Bibliography:
  [1] page=4 | section=4. Methods
      quote: we employ a machine learning tool called ' Elastic net ' that eliminates the weights of the least critical
             features (Zou & Hastie, 2005).
  [2] page=4 | section=4. Methods
      quote: we examine the statistical importance of particular characteristics with Fama-MacBeth (FM) regressions (1973,
             FM hereafter).
  [3] page=5 | section=4. Methods
      quote: In the last step, we run the multivariate FM regressions that simultaneously consider all important variables.
  [4] page=9 | section=6. Conclusions
      quote: The dependent variable is the stock weekly log-return.

--------------------------------------------------------------------------------------------------------------
RE-TEST RESULTS (compact summary)
--------------------------------------------------------------------------------------------------------------
 Paper ID       Model GT_Foundational Paradigm New_Agent_Foundational Paradigm Match_Foundational Paradigm GT_ML Learning Type New_Agent_ML Learning Type Match_ML Learning Type GT_ML Problem Type New_Agent_ML Problem Type Match_ML Problem Type GT_Deep Learning Used New_Agent_Deep Learning Used Match_Deep Learning Used GT_Specialised Paradigms New_Agent_Specialised Paradigms Match_Specialised Paradigms Match_All_5
2021 - 28 gpt-4o-mini                    Mixed                           Mixed                       MATCH          supervised                 supervised                  MATCH         regression                regression                 MATCH                 False                        False                    MATCH                       []                              []                       MATCH       MATCH

,Paper ID,Model,GT_Foundational Paradigm,New_Agent_Foundational Paradigm,Match_Foundational Paradigm,GT_ML Learning Type,New_Agent_ML Learning Type,Match_ML Learning Type,GT_ML Problem Type,New_Agent_ML Problem Type,...,Match_Deep Learning Used,GT_Specialised Paradigms,New_Agent_Specialised Paradigms,Match_Specialised Paradigms,overall_validated_reasoning,audit_commentary,confidence,validated_bibliography_count,validated_bibliography_lines,Match_All_5
0,2021 - 28,gpt-4o-mini,Mixed,Mixed,MATCH,supervised,supervised,MATCH,regression,regression,...,MATCH,[],[],MATCH,The study employs both machine learning and cl...,No specialised paradigms were found in the stu...,0.9,4,"[[1] page=4 | section=4. Methods, quote: w...",MATCH

# Open AI Direct PDF Upload

In [8]:
paper_path = r"C:\Users\sahil\OneDrive\PhD\3. Empirical Study\Methodological Workflow\Pilot_Evaluation\DATA_sample_10\2023 - 58.pdf"

In [9]:
from openai import OpenAI
client = OpenAI()

file = client.files.create(
    file=open(paper_path, "rb"),
    purpose="assistants"   # important
)

In [11]:
vector_store = client.vector_stores.create(
    name="papers_store"
)

In [12]:
client.vector_stores.files.create(
    vector_store_id=vector_store.id,
    file_id=file.id
)

VectorStoreFile(id='file-Ws7WK7ZM3Mhi7VbZUWybCJ', created_at=1775281774, last_error=None, object='vector_store.file', status='in_progress', usage_bytes=0, vector_store_id='vs_69d0a66be3f8819186f367a166a7ddbf', attributes={}, chunking_strategy=StaticFileChunkingStrategyObject(static=StaticFileChunkingStrategy(chunk_overlap_tokens=400, max_chunk_size_tokens=800), type='static'))

In [18]:
prompt_path = r"C:\Users\sahil\OneDrive\PhD\3. Empirical Study\Methodological Workflow\prompts\dsrp\modelling\foundational\foundational_classifier.yaml"

In [19]:
import yaml

with open(prompt_path, "r") as f:
    config = yaml.safe_load(f)

In [20]:
system_prompt = config["instructions"]   # this is your full classifier logic
temperature = config.get("temperature", 0)

In [23]:
response = client.responses.create(
    model="gpt-4o-mini",
    temperature=0,
    tools=[{
        "type": "file_search",
        "vector_store_ids": [vector_store.id]
    }],
    input=[
        {"role": "system", "content": system_prompt},
        {
            "role": "user",
            "content": "Analyse the paper and return the classification. Focus on methodology. Return ONLY JSON."
        }
    ]
)

In [24]:
print(response.output_text)

```json
{
  "foundational_paradigm": "Mixed",
  "confidence": 0.9,
  "reasoning_explanation": "The study employs both classical statistical methods and machine learning techniques. It utilizes Latent Dirichlet Allocation (LDA) for topic modeling, which is a machine learning approach, alongside visual content analysis (VCA) and spatial analysis, which are more traditional statistical methods. The combination of these methodologies indicates a mixed approach, as the study aims to leverage the interpretability of statistical models while also utilizing the predictive capabilities of machine learning.",
  "bibliography": []
}
```

In [28]:
response

Response(id='resp_0aa2331526ed4ddb0069d0a6c7e4988197a677afee7128de74', created_at=1775281864.0, error=None, incomplete_details=None, instructions=None, metadata={}, model='gpt-4o-mini-2024-07-18', object='response', output=[ResponseFileSearchToolCall(id='fs_0aa2331526ed4ddb0069d0a6c8ee6081978e957cb37b3dd2df', queries=['methodology', 'research design', 'statistical analysis', 'machine learning', 'modeling approach'], status='completed', type='file_search_call', results=None), ResponseOutputMessage(id='msg_0aa2331526ed4ddb0069d0a6ce2a848197b5d5678492a81160', content=[ResponseOutputText(annotations=[AnnotationFileCitation(file_id='file-Ws7WK7ZM3Mhi7VbZUWybCJ', filename='2023 - 58.pdf', index=603, type='file_citation'), AnnotationFileCitation(file_id='file-Ws7WK7ZM3Mhi7VbZUWybCJ', filename='2023 - 58.pdf', index=603, type='file_citation')], text='```json\n{\n  "foundational_paradigm": "Mixed",\n  "confidence": 0.9,\n  "reasoning_explanation": "The study employs both classical statistical methods and machine learning techniques. It utilizes Latent Dirichlet Allocation (LDA) for topic modeling, which is a machine learning approach, alongside visual content analysis (VCA) and spatial analysis, which are more traditional statistical methods. The combination of these methodologies indicates a mixed approach, as the study aims to leverage the interpretability of statistical models while also utilizing the predictive capabilities of machine learning.",\n  "bibliography": []\n}\n```', type='output_text', logprobs=[])], role='assistant', status='completed', type='message')], parallel_tool_calls=True, temperature=0.0, tool_choice='auto', tools=[FileSearchTool(type='file_search', vector_store_ids=['vs_69d0a66be3f8819186f367a166a7ddbf'], filters=None, max_num_results=20, ranking_options=RankingOptions(hybrid_search=None, ranker='auto', score_threshold=0.0))], top_p=1.0, background=False, completed_at=1775281874.0, conversation=None, max_output_tokens=None, max_tool_calls=None, previous_response_id=None, prompt=None, prompt_cache_key=None, prompt_cache_retention=None, reasoning=Reasoning(effort=None, generate_summary=None, summary=None), safety_identifier=None, service_tier='default', status='completed', text=ResponseTextConfig(format=ResponseFormatText(type='text'), verbosity='medium'), top_logprobs=0, truncation='disabled', usage=ResponseUsage(input_tokens=16263, input_tokens_details=InputTokensDetails(cached_tokens=0), output_tokens=170, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=16433), user=None, billing={'payer': 'openai'}, frequency_penalty=0.0, presence_penalty=0.0, store=True)

In [29]:
from openai import OpenAI

client = OpenAI()

user_query = system_prompt

results = client.vector_stores.search(
    vector_store_id=vector_store.id,
    query=user_query,
)

In [35]:
def format_results(results):
    formatted_results = ''
    for result in results.data:
        formatted_result = f"<result file_id='{result.file_id}' file_name='{result.file_name}'>"
        for part in result.content:
            formatted_result += f"<content>{part.text}</content>"
        formatted_results += formatted_result + "</result>"
    return f"<sources>{formatted_results}</sources>"

In [36]:
formatted_results = format_results(results.data)

'\n'.join('\n'.join(c.text) for c in result.content for result in results.data)

completion = client.chat.completions.create(
    model="gpt-4.1",
    messages=[
        {
            "role": "developer",
            "content": "Produce a concise answer to the query based on the provided sources."
        },
        {
            "role": "user",
            "content": f"Sources: {formatted_results}\n\nQuery: '{user_query}'"
        }
    ],
)

print(completion.choices[0].message.content)

AttributeError: 'list' object has no attribute 'data'

In [37]:
client.vector_stores.list()

SyncCursorPage[VectorStore](data=[VectorStore(id='vs_69d0a66be3f8819186f367a166a7ddbf', created_at=1775281772, file_counts=FileCounts(cancelled=0, completed=1, failed=0, in_progress=0, total=1), last_active_at=1775282152, metadata={}, name='papers_store', object='vector_store', status='completed', usage_bytes=123983, expires_after=None, expires_at=None, description=None), VectorStore(id='vs_69d09b560d688191854c9a17129b4b42', created_at=1775278934, file_counts=FileCounts(cancelled=0, completed=1, failed=0, in_progress=0, total=1), last_active_at=1775278936, metadata={}, name='papers_store', object='vector_store', status='completed', usage_bytes=123983, expires_after=None, expires_at=None, description=None), VectorStore(id='vs_69d09b20475481919e3c5d99dcd160e9', created_at=1775278880, file_counts=FileCounts(cancelled=0, completed=1, failed=0, in_progress=0, total=1), last_active_at=1775278881, metadata={}, name='papers_store', object='vector_store', status='completed', usage_bytes=123983, expires_after=None, expires_at=None, description=None), VectorStore(id='vs_69d092b6185c8191a43385ac4148f1c8', created_at=1775276726, file_counts=FileCounts(cancelled=0, completed=1, failed=0, in_progress=0, total=1), last_active_at=1775276732, metadata={}, name='papers_store', object='vector_store', status='completed', usage_bytes=137894, expires_after=None, expires_at=None, description=None), VectorStore(id='vs_69d091a3fc448191a1792a658faadced', created_at=1775276452, file_counts=FileCounts(cancelled=0, completed=1, failed=0, in_progress=0, total=1), last_active_at=1775276470, metadata={}, name='papers_store', object='vector_store', status='completed', usage_bytes=81250, expires_after=None, expires_at=None, description=None)], has_more=False, object='list', first_id='vs_69d0a66be3f8819186f367a166a7ddbf', last_id='vs_69d091a3fc448191a1792a658faadced')

# Run using Open AI Vector Store

In [38]:
from modules.tools import add_files_to_openai_vector_store

result = add_files_to_openai_vector_store(
    file_paths=[
        "my_papers/paper1.pdf",
        "my_papers/paper2.pdf",
    ],
    vector_store_name="phd-methodology-store"
)
print(result)

OpenAIVectorStoreError: File not found: my_papers/paper1.pdf